### ISSUE TITLE
Binaries not being free is a security risk to the users of the product.

### ISSUE THREAD

**Issue by duaneking** [pgmodeler/pgmodeler#1009]
The fact your charging for binaries is a huge security red flag and it makes the project hostile to its user base.

By charging for binaries that are secure and known to be exactly what the code that is checked in is, you are not only making bug reports and debugging harder on yourself, but you are also effectively telling people who want the binaries for free that their only option to get them for free is to find a secondary website to get them from.  Sadly this often means a website that may have injected a virus or trojan horse into the application.  This means people who want to use this software are now at risk of data theft, identity theft, or worse, all because you did not offer free binaries.  This means fewer people will ultimately want to help make it better.

This is a huge problem and can also be taken as a bad thing that hurts your personal reputation; I'm sure you are not a greedy or bad person by nature, but asking people to pay for binaries or risk having their lives destroyed by data theft or computer infection opens up the idea that you do not value their security or safety an can hurt your personal reputation in the community.  Is this the case?

If you care about the users of this project, and you care about this project, please enable up to date free downloads and stop the profit-seeking actions that put your reputation and the lives of your users at risk.

These downloads don't cost you anything, GitHub is free to you, so there is no reason not to do it.

**Comment by rkhaotix** [comment]
I've stopped to talk about why I started to charge for binaries but since I found your words interesting I'll do that.

> By charging for binaries that are secure and known to be exactly what the code that is checked in is, you are not only making bug reports and debugging harder on yourself, but you are also effectively telling people who want the binaries for free that their only option to get them for free is to find a secondary website to get them from.

No. I think you're a bit wrong.

Well, this project has almost twelve years and in its 6 initial years I was distributing pgModeler binaries "for free". The problem was that I was paying for giving users free package. How? First, staying away from my family to dedicate myself, alone, to this software. Second, I was in the need of buying a new equipment to improve the software in its initial releases and I did that and did not ask for a single penny to my users. Third, I have bills to pay. I love this project, I love what it has turned, but love does not pay my bills nor feed my family. Sorry if it sounds a bit harsh.

I'm certain that you know that... but being an opensource ruled by GPL3.0 I can charge for its binaries but with the obligation (not a problem to me) to deliver the source code. I even go beyond... I grant the user a complete, unmodified, source code with a complete tutorial on how to compile and make the software work (https://www.pgmodeler.com.br/support/installation). Even when people can't compile pgModeler for themselves I help.

> Sadly this often means a website that may have injected a virus or trojan horse into the application. This means people who want to use this software are now at risk of data theft, identity theft, or worse, all because you did not offer free binaries. This means fewer people will ultimately want to help make it better.

And what's the difference from distributing it for free in binary form for free? A malicious person can grab the binary from the official site, inject a virus/worm/trojan and redistribute the infected package in another web site, even a perfect copy of the official web site. Even the source code can be used to create a malicious binary and redistributed to make bad things with the users' data. This is a threat of the same proportion as you told... What I want to tell is no matter the way the software is distributed, paid or not, if one has the interest to cause harm to other people, he/she will do! This is why I always warn people to get the packaged software from trusted sources like the project's site itself or from the several Linux distro repos (Ubuntu, Fedora, Debian, ArchLinux).

By charging for binaries never diminished the feedback about the software. Instead, it helped me a lot in fix bugs and make new features for it. The paid version of the software never let the users away from this project. Fortunately, there are users who like to pay for the convinience to have a software ready to use.

> This is a huge problem and can also be taken as a bad thing that hurts your personal reputation; I'm sure you are not a greedy or bad person by nature, but asking people to pay for binaries or risk having their lives destroyed by data theft or computer infection opens up the idea that you do not value their security or safety an can hurt your personal reputation in the community. Is this the case?

> If you care about the users of this project, and you care about this project, please enable up to date free downloads and stop the profit-seeking actions that put your reputation and the lives of your users at risk.

Honestely? I don't think that charge for a open source software can hurt my reputation. I really worry about user's personal data but, again, being paid or not, we have no guarantee that a person with bad intentions will use the software to stole data or harm people's machine. It's up to the user to select the correct source when getting the software as well have a good anti virus on his/her machine. This is why I always alert my users to take care from where they get the software. People next to me know me well,  my users know me well. So, if the problem is my personal reputation.... Well, I'm really confident about it, since the very moment I decided to charge for binaries and receive support from all over the world! 

> These downloads don't cost you anything, GitHub is free to you, so there is no reason not to do it.

Yes they cost! The project's site is not hosted in GitHub and I pay for a professional hosting service. I pay to Github too so I can use their private repository services. And yes, I have my reasons to charge for binaries, and many many users understand that and buy packages or even do generous donations to keep this project alive! Thanks to them, this project reached levels of maturity I've never imagined! Because, by receiving a small amount of money from my work I feel commited to give them a response in form of improvements! Those who don't want to pay, grab the source and compile it (asking for help when needed). Fortunately, this formula is working well and I don't have the intention to change it so soon. The problem I see in these twelve years leading this project is that a minority of people doesn't like to pay for open source software. They want everythig ready-to-use and don't like to have a minimal effort to make things work by their hands. 

That's it.

**Comment by duaneking** [comment]
You are using fallacious arguments; Please, keep this civil.

1. You are required by the GPL to give them the code, so claiming its something you do out of the goodness of your heart isn't accurate. 

2. A binary for free would mean that nobody has any reason to go to a third party for packages for specific platforms (such as mac, or windows).  Thus, any argument that "its possible" that a third party can use the code in a malicious way is a moot point because nobody who needed a binary would have to use a third untrusted party if they could just get the mac/windows binaries themselves easily. ANd if they still chose to, that's on them, but at least a safe option now exists in that scenario if you provided one.

3. If you care about security, you will allow people to download free binaries. They don't need to be the most recent version, just offer the prior stable version if you really must be greedy about it.

4. You are not forced to spend money on marketing, a professional hosting service, a merchant account, an e-commerce website, etc. You choose to.  That is up to you. That is all under your control.

5.   It is not always possible for a person to compile a binary for themselves if they need one.

6.  The very idea of open source software is just that, that it works and it's free.  It's only reasonable that people would also assume that the software works as described. It's not a bug or defect that people expect open source software to be free, it's a core feature.

**Comment by rkhaotix** [comment]
> You are using fallacious arguments; Please, keep this civil.

And it is not civil? I never intended to offend you...
The problem is, you're not respecting me, my point of view or my reasons. You're just saying things as if I'm a greedy person. You don't know me so, please, measure your words.

> You are required by the GPL to give them the code, so claiming its something you do out of the goodness of your heart isn't accurate.

My English is not that good and I think you did not understand what I've said. Again, I said that I GO BEYOND and provide anyone a complete step-by-step on how to compile and run the software. Those who don't have success on the task can contact me anytime so I can provide the needed assistance. Now, deliver the source is something I do with a great pride I don't even need to be obligated by the GPL. 

> If you care about security, you will allow people to download free binaries. They don't need to be the most recent version, just offer the prior stable version if you really must be greedy about it.

Do free downloads are the pass for the "care about security" world? This argument is weak, sorry. I don't buy it. Just offer older versions of the software can become a big problem to me. Well, you don't know my project as I do but it constantly changed and improved and some features are dropped and new ones added (as any project in constant enhancement)... People will start to report bugs in older versions that are already fixed on newer ones. Another example, they will start to complain about files generated in older versions that aren't compatible with newer releases... and many other problems. I'm pratically alone coding this project (eventually a pull request is done, fortunately) so if I can avoid problems like this I'll do! Just being practical.

It seems to me that you just can't accept the fact that I have an open source software and charge for the service of delivering pre-compiled packages (you're not the first), alleging that this is a security flaw because I forcibly lead people (who supposedly don't want to pay) to third party sites with modified versions of my software and all those random words about personal data theft, reputation and etc. A "moot point" to me. 

> You are not forced to spend money on marketing, a professional hosting service, a merchant account, an e-commerce website, etc. You choose to. That is up to you. That is all under your control.

Yes, I know that. If I think all these things are needed, I'll use them... as I do today! I'm certain that putting a bit of my money on these services worth it and made pgModeler reach even more users. This does not mean that I received more money... the user base grown and the collaboration increased. More people use pgModeler being paid versions of it or not!

> It is not always possible for a person to compile a binary for themselves if they need one.

Hm.. and I don't know that? That's why I give them free support, of course, within my availability and time.

> The very idea of open source software is just that, that it works and it's free. 

And where did you read that pgModeler isn't free or barely works? Charge for binaries makes the project automatically non-free? Please, do not confuse things... pgModeler IS FREE. Everyone can take the source, modify, redistribute and even generate binaries for themselves.... does this not mean to be free? And what if I distribute only the source? You would be here talking about how absurd is an open source project that do not offer binaries?

> It's only reasonable that people would also assume that the software works as described. It's not a bug or defect that people expect open source software to be free, it's a core feature.

I don't get it. Of course they expect a functional software and this is not different with pgModeler. What I deliver be the source or binary, both are fully functional. There is no trick to make the software run.

Well, we can spend weeks defending our points. But I'll certainly avoid it... just because you're not the first one that complains about the model I've adopted and I'm pretty sure that you'll not be the last. I'm just tired of this kind of discussion.

But what gives me energy to keep working on it, despite all those who complain a lot, is that there are people who can compile the software and still decide to pay for binary packages just to support my work or even those who want to pay just  because they don't want to have the work to compile it, or those who just use the software from third party sources (like Linux distros) and want to help by donating, suggesting new features, reporting bugs or just spending their time giving friendly words because pgModeler somehow helped them on their respective projects. And is for those people that I'll keep working on pgModeler!

Now, if you don't mind, let's stop this fruitless discussion? 
Stay well.

**Comment by Zynde** [comment]
I paid and I love the product.

**Comment by archenroot** [comment]
The license fee in case of this project I feel like very symbolic against all cool features it has. Also @rkhaotix is fair person and help you on extension/bugs quickly when you need it. This discussion reminds me that I might renew my license to support you on this journey!

**Comment by rkhaotix** [comment]
Thank you so much @archenroot  and @Zynde for the support! I'm glad to see that there's still people who believe in my work and are willing to give some contribution to it! You can count on me anytime.

What I can't understand is the polemics around the "business model" (let's put this way) that I've adopted... If I was denying the access to the source code or have closed the source code and started to charge exaggerated prices for the binaries I think that the discussion would be valid... But, what I'm trying to do is to get a bit of money from my hard work. People make their money using my project... why I can't do the same? :)

Anyways, he has the legit right to protest (without offend, of course)... and on the other hand, I have the right to keep working on this project the way I decide to!

**Comment by nboisteault** [comment]
Thank you for your great work ! Some good open source softwares die because they lack money. There is nothing wrong charging the binaries IMO.

**Comment by mdsystems** [comment]
I will also chip in here and say I think it is perfectly OK for you to charge for binaries. If someone is concerned about security, build from source (having checked that they are happy with the source first, naturally). Using an application written by someone else is a security risk anyway, unless you check it yourself, thoroughly. 

Keep doing as you are and thank you for your contribution to database developers who use PostgresQL.

**Comment by rkhaotix** [comment]
@mdsystems Thank you so much for the support! I'm really happy that my work is really appreciated all over the world! :)

Yeah, I think you're right. We should close this issue... there's no reason to it to stay open. 
Thanks.
