### ISSUE TITLE
Linux installer forgot to add plugins directory

### ISSUE THREAD

**Issue by webaaz** [pgmodeler/pgmodeler#1035]
Hi!

I run pgmodeler-0.9.0-linux64.run and the install is done.
But when I launch PGmodeler, there's a bug beacuase the directory /opt/pgmodeler/plugins doesn't exist.
It's not hard to fix, but it would be cool if the installer do it!

Thanks

**Comment by rkhaotix** [comment]
Yep! Currently, it's pgModeler that tries to create that directory but I'll change that behavior and let the installer create it or even disable the plugins directory since we don't have official plugins yet.

**Comment by tschoening** [comment]
> Unable to write the file or directory `C:/Program Files (x86)/pgmodeler/plugins'! Make sure the output directory exists, or if the user has write permissions over it!

This problem applies to Windows as well and the approach to create it at runtime in the installation folder is a bad design decision, because by default users don't have writer permissions in that folder. So please create it in the installers, which are executed using admin permissions most likely, create it in `%APPDATA%\Local\pgmodeler` during runtime or simply don't create it at all.

**Comment by titanofold** [comment]
It's fine to have a `/usr/lib{,32,64}/pgmodeler/plugins` directory, but pgmodeler shouldn't complain about regular user not being able to write to it.

To let the user install plugins, it should be done within the $HOME directory. Many applications will create a directory structure like `~/.appname/plugins`.
