### ISSUE TITLE
Assignment of a name which contains invalid characters!

### ISSUE THREAD

**Issue by jonny7** [pgmodeler/pgmodeler#1076]
I am trying to import a schema in which has tables such as `tableA+tableB`. I didn't name these tables, but they seem valid in my Postgres schema as I'm looking at it in PGAdmin. But I get the following error: `Assignment of a name which contains invalid characters!`

**Comment by rkhaotix** [comment]
This is a problem similar to this #800

**Comment by jonny7** [comment]
@rkhaotix, just reading the docs for Postgres and MySQL, I'm not even sure that a `+` sign should be allowed as an identifier. But the framework I'm using created it.

**Comment by rkhaotix** [comment]
Hi @jonny7 

Actually, PostgreSQL allows any special character in the middle of objects' names since the user double quote it... In your case the valid name for your case should be "tableA+tableB". The limitation here is on pgModeler which has a limited set of allowed "special chars". The solution is quite simple, I just need to add the ```+``` as an accepted character.

But, IMHO, this kind of naming is such a bad design and the framework you're using should review this convention. Just a thought! :)

**Comment by jonny7** [comment]
@rkhaotix I agree and so do the guys on the framework. Thank you for taking the time to answer my question 👍

**Comment by rkhaotix** [comment]
No problem 😁
