### ISSUE TITLE
PGModeler does not play nice with AWS RDS Extensions

### ISSUE THREAD

**Issue by dtiziani** [pgmodeler/pgmodeler#1089]
When I use some extension on database, such as uuid-ossp, pgmodeler tries to put it in a schema, such as public.uuid-ossp and it causes an error on aws postgres.

As a workaround, I have to create the extension on pgmodeler model and disable sql code generation, and handle it outside pgmodeler.

Is it some particularity of AWS RDS Postgres? Or some bug on pgModeler?

Thanks and keep up the nice work! I'll report some more bugs I've found!

pgmodeler version 0.9.1-alpha

**Comment by rkhaotix** [comment]
Actually, pgModeler reproduces the same behavior as the PostgreSQL by allowing to assigning a schema to the extension, because objects created by the extension can be installed in that schema. If no schema is provided the objects of the extension is created in the default schema (public). See here: https://www.postgresql.org/docs/10/static/sql-createextension.html

The only problem I see with pgModeler is that it is visually showing extensions under schemas which is wrong I agree. I'll try to provide a fix quickly.

**Comment by dtiziani** [comment]
Hi @rkhaotix , thanks for the response. Actually, the issue I'm having is that I cannot create an extension on my model that is schemaless, such as required in AWS RDS Postgres. As I understand, it is not the default behaviour for postgres (somewhat Amazon changed that).

Is there a way to support it on pgModeler? If not, I can keep my workaround, but I believe some other users might be affectec by it, then I'll suggest adding it to the documentation as a workaround.
If an example of the complete scenario is welcome, I can create one here for you. (with printscreens for each step)

Thanks!

**Comment by rkhaotix** [comment]
There's no need to demonstrate. I understood :)
I've created a patch that move the extension to database level making them schemaless leaving them according to the official docs. The next release will introduce the fix. :)

**Comment by rkhaotix** [comment]
Actually, it was my fault... I interpreted the docs wrongly. Fortunately, the fix was really easy to make.
