### ISSUE TITLE
Linux screen switch wipes open dialogs

### ISSUE THREAD

**Issue by snhirsch** [pgmodeler/pgmodeler#1091]
I've just been burned by this for the umpteenth time and am starting to consider it a major nuisance.  To duplicate:  

- Start working with a project on the KDE desktop under Linux
- Open a new table dialog and start filling things in
- Switch to another desktop space (as you might to check information that needs to be in the dialog), then switch back

Everything you have entered will be gone.  I have seen this happen even when switching focus to another window on the same desktop, though not all the time.  It may well be a Qt issue, but it's a real PITA and time waster.

**Comment by rkhaotix** [comment]
I'm not able to reproduce the problem.. Tried several times and everything is fine.

I've one suspect but I'll change the code only if I can reproduce it on my development enviroment. What is the Qt/KDE version in use?

**Comment by rkhaotix** [comment]
Now I could reproduce... the window must be minimized. I'll investigate.

**Comment by rkhaotix** [comment]
Are you able to compile pgModeler? Try this commit 815eee4

The problem was that in the past the editing forms were singletons and I needed clear them everytime they was hidden to be reused by another object. Now, we instantiate a new form for each object being edited so no need to clear the forms anymore. I've removed the old (uneeded) code and seems to work.

I'll be grateful if you can test it on your side.

**Comment by rkhaotix** [comment]
Yes. 
Also, I've tested on my development environment and it worked fine. If you see that the issue still persists feel free to reopen the issue
