### ISSUE TITLE
skip validation process,can not open .dbm file . how can i fix the corrupted file

### ISSUE THREAD

**Issue by jintaolee** [pgmodeler/pgmodeler#1126]
**Bug description**
  when I save the design model file . I skip the validation process. I can not open the .dbm file anymore

 
**Info about your desktop**
 - OS: mac 
 - Version:10.13.3  
 - pgModeler version:v0.9.1
 

**Stacktrace**
     pgModeler 0.9.1-beta1 command line interface.
Starting model fixing...
Loading input file: /Applications/pgmodeler.app/Contents/MacOS/schemas/npi.dbm
Fixed model file: /Applications/pgmodeler.app/Contents/MacOS/schemas/npi_fixed.dbm
Extracting objects' XML...

[1] src/pgmodelercli.cpp (598)
  void PgModelerCLI::extractObjectXML()
    [ERR_CUSTOM] Invalid input file! It seems that is not a pgModeler generated model or the file is corrupted!

[0] src/pgmodelercli.cpp (496)
  int PgModelerCLI::exec()
    [ERR_CUSTOM] Invalid input file! It seems that is not a pgModeler generated model or the file is corrupted!

**Comment by rkhaotix** [comment]
Sorry, but I can't do much for you. According to the email I've sent you the model you in question npi.dbm file is empty (zero bytes), if it was only corrupted in such way that the objects were preserved but in the wrong place I could fix the model manually.

The problem is that you ignored the invalidation state of your model and kept saving it without validate. One advice I give you, do not ignore the warning messages of the tool about the need of validating the model and use the "Save anyway" button if and only if you are pretty sure that your model will not be malformed when reopening the application.

**Comment by ChandraNarreddy** [comment]
Hi, ran into this same issue and now am unable to recover my model. What about recovering an earlier version of the model from autorecovered files. Would you be able to point me to the location in MacOS where PGModeler autorecovers from. I am hoping to get to any relics from there.
