### ISSUE TITLE
Support 1-1 relationships for shadow tables...

### ISSUE THREAD

**Issue by mgajda** [pgmodeler/pgmodeler#1185]
**Feature description**
_Allow 1-1 obligatory relationships for fine-grained access control._

Since we can either GRANT SELECT/UPDATE rights on specific columns only, or filter them to specific rows (row level security), we might need to create *shadow tables* for private user account details etc.
Non-owners may only use primary table to lookup the name and id of the object, whereas owners may change private details.
Thus everybody would have access to *uid*, and *name* columns:
```
GRANT SELECT(uid, name) ON TABLE users TO knownUser;
```
And of course user himself/herself can edit own details:
```
CREATE POLICY change_private_details ON shadow
    AS PERMISSIVE
   FOR SELECT/UPDATE
   TO knownUser
   USING (user_id=jwt.claims.user_id)
```
Allowing to model `shadow` table by mandatory 1-1 relationship allows this access control to work, whereas forcing `shadow` and `user` to be fused to a single table means that we cannot use the fine grained access control scheme.

**Additional info**

Or we can wait til PostgresSQL team implements a combination of row level security and column access restriction (which may possibly never happen).

**Comment by rkhaotix** [comment]
The absence of a mandatory 1:1 relationship was a project decision because, in theory, translating it to model/code could lead to fusion of the tables which is not a desired behavior.

Despite this limitation, your free to create the relationship in the way want by add manually the foreign key (s) and unique constraint (s) in order to simulate the feature you need.
