### ISSUE TITLE
Add new layers of diagramming

### ISSUE THREAD

**Issue by Maxzor** [pgmodeler/pgmodeler#1205]
Domain : Design section, impacts possibly core lib too.

SQL standard is pretty obsolete, and, especially, schema implementations, in major databases including postgre, are exceptionally poor : there is no inheritance nor composition notions at the schema level.

The feature proposed is to add hierarchical layers of table classification, grouping visually tables in sub-entities.
You could display for example :
Schema A - Layer 1 - Table1
Schema A - Layer 1 - Table2
Schema A - no layer - Table3
Schema A - Layer 2 - SubLayer 1 -...(SubLayer n)...- Table 4
Schema A - Layer 2 - Table5

Maybe an option would be to subclass schemaview into a layerview?

**Comment by rkhaotix** [comment]
There's a feature scheduled to work as an additional visual segmentation: workspaces. They will group visual objects by a numeric identifier related to a workspace. The user will be able to switch between the workspaces making objects visible or not. 

About the layers you are proposing, why create another object for visual separation ? We already have schema boxes and tags. Also, add layers can make the code that handles visual operations more expensive to run (which I am avoiding at the moment due to performance hits I trying to solve).

**Comment by Maxzor** [comment]
Right, pgmodeler's tag feature can be considered vastly sufficient.
