### ISSUE TITLE
[Enhancement discussion] Diff tool

### ISSUE THREAD

**Issue by Maxzor** [pgmodeler/pgmodeler#1220]
The diff module is a great idea, and I think it could become better in various ways.
Here is an attempt to catalog desired features :

- partial diffs. Diff between a part of the model and/or a part of the database (granularity at schema?).

- track table move between schemas. OIDs could be used for that as discussed, among other options.

- dual-way diffs. At the moment you can choose input type as current model or database, but output type does handle database type only, and not model. In another wording you can update your database with changes made to the model for now : it could be useful to also be able to update the model from the database.

- insert your request here!

**Comment by Maxzor** [comment]
-  dual way diff : there is actually a good feature on "objects metadata" : it will update an erd with metadata from another erd, as well-explained in the doc. This is a clever trick to accomplish the reverse of the current diff. The feature could be better related to the diff one I guess!

**Comment by Maxzor** [comment]
About object metadata being far away from export import and diff :
what about a "sync center" -or some better name- widget, where all the features would be grouped? (model-model, model 1:n - 1:n database, db-db...)

**Comment by Maxzor** [comment]
![pgm_io_center](https://user-images.githubusercontent.com/16599683/74102243-f5fa4b00-4b41-11ea-89ba-9cd0488ce84b.png)

**Comment by FGRibreau** [comment]
I want to use pgmodeler diff tool through its CLI capabilities to generate a diff and apply it just like Kubernetes, Terraform, ...

With Kubernetes, Terraform (and so on) the developer always work on the **target state** (either in yml files or tf files) and then the CLI or backend makes a diff between the `current state` and a `target (plan)`.

That's what is missing in SQL development workflow. 

We need to work and think only about the target state and never handle migration files manually, we have CI and CD to make the checks for us (TL;DR: load a dump of the production database, duplicate traffic (e.g. go-replay), generate a diff between the target state and the production state, try to run the generated SQL output on the duplicated database, if it work in less than xxx ms then we are good to go (considering the other tests went right)).

Currently we improved a lot of what was in [SubzeroCLI](https://docs.subzero.cloud/iterative-development-workflow/) workflow and are now relying on pgModeler instead of apgdiff but it could be even greater *without* migrations. Just like we do with Kubernetes, Terraforms...

SQL let us do that thanks to introspection capabilities but we are not there yet because there are still some bugs https://github.com/pgmodeler/pgmodeler/issues/1478 https://github.com/pgmodeler/pgmodeler/issues/1479 in pgModeler. ... Even if pgModeler is way on top of the [alternatives](https://twitter.com/FGRibreau/status/1316321226407714816).
