### ISSUE TITLE
Some pgmodeler performance benchmarks - Ubuntu / Windows / VM / WSL

### ISSUE THREAD

**Issue by Maxzor** [pgmodeler/pgmodeler#1244]
Hello,
I ran some tests to see how performance behaves between configs, and figured I might share aswell. If you have different proportions, or I messed up in something, please add your numbers down :)

All tests were done on :
- a 4/8-coreI7 #8th gen, 16GB-RAM laptop.
- Qt5.12, Postgres11, PgModeler commit #e3edb12, and a medium-large database model of 1700 tables and 3k relationships.

***Ubuntu 18.04 native :***
Initial design render - 1m15s
Cli --fix-model - 1m13s

***Windows 10 latest, "native" (Msys2/minGW64 build) :***
Initial design render - 2m47s
Cli --fix-model - 2m17s

***Windows Subsystem for Linux (WSL) - Ubuntu 18.04 on win10, MobaXTerm GUI:***
Initial design render - 2m42s
Cli --fix-model - 1m52s

***VirtualBox 5.2.12 Host win10, guest Ubuntu 18.04 (4CPU 8GB RAM)***
Initial design render - 2m27s
Cli --fix-model - 2m12s

**Comment by Maxzor** [comment]
It bugs me that the performance of windows minGW is THAT bad.
There is a 2x performance it compared to native linux!
Have I missed something in the compilation?

**Comment by rkhaotix** [comment]
Well, I'm used to that performance on MingW. I don't know if it's Qt's fault or a performance issue of MingW/msys2. We have to consider that things aren't native on that subsystem and that make applications running on top of it a bit slower compared to Linux. 

Also, pgModeler is a bit slower too on macOs. The thing is. . a multiplatform app will always perform better on a certain system and worse on another. There's always a trade off. 

But in general I really like the performance on all system but on Linux is where pgModeler shines. I'm suspect to say that because Linux is my preferred OS :)
