### ISSUE TITLE
Shortcut from protected column to relationship

### ISSUE THREAD

**Issue by oliversalzburg** [pgmodeler/pgmodeler#1298]
**Feature description**
When you have a relationship between two tables and you edit the properties of the table that holds the FK, you are unable to make any adjustments to the column that holds the FK. 

I commonly have the need to do this, because I, for example, want to mark the column as `NOT NULL`.

What I have to do instead, is to find the line that represents the relationship and open the properties for the relationship through interacting with that line, the label in the middle of it, or one of its endpoints. This can be tricky, as the mentioned objects can sometimes be partially or fully obscured by other elements.
I can also search the relationship from the Objects panel, but that can also be somewhat cumbersome, especially if you haven't taken care of properly naming your relationships.

My suggestion would be to provide a shortcut from one dialog to the other. Where it says "This object is protected thus no change in form will be applied to it." (also note the missing "this" before "form" here 😉), maybe add a link "Edit the associated relationship instead" that opens the properties of the relationship.

**Sample image**
![image](https://user-images.githubusercontent.com/1658949/60184028-a0c62f00-9827-11e9-838d-39eb90c0fc5c.png)

**Comment by rkhaotix** [comment]
pgModeler already has such feature (actually, almost close to what you need). 

In order to handle the relationship that generates a certain column you have to right click a column generated by a relationship (on the canvas) and choose "Open relationship". By default, these columns are the one in green foreground and italic style. 

![rel_shortcut](https://user-images.githubusercontent.com/2205476/60189925-22a66000-9808-11e9-9420-1e6898cbbc86.png)

**Comment by oliversalzburg** [comment]
Awesome. I was not aware of it, even though it's right in my face :D Thanks for the heads-up.
