### ISSUE TITLE
Validation is not performed by default

### ISSUE THREAD

**Issue by oliversalzburg** [pgmodeler/pgmodeler#1301]
**Feature description**
Consider the following useage scenario:

I open pgModeler, then open my model. I make a couple of changes and want save them. pgModeler shows the following prompt:

![image](https://user-images.githubusercontent.com/1658949/60332332-e3f2e000-9996-11e9-97b7-64eeaa2b5988.png)

I click **Validate**. The validation panel opens and shortly after shows the following status:

![image](https://user-images.githubusercontent.com/1658949/60332376-fcfb9100-9996-11e9-832d-83ff23dc704d.png)

This is due to the fact that, while I have a database connection configured that could be used for validation, it is not selected whenever pgModeler is started. It has to be selected again after every start.

First of all, I don't think the validation should complete successfully if it wasn't executed. The previous dialog suggests to me that I don't want to save a model that has not been validated, but the default behavior after that leads to exactly this.

Second, it would be nice if the database connection could be remembered, so that it doesn't need to be reselected every time.

**Comment by rkhaotix** [comment]
Your connection is marked as default for validation? If not, see here:
https://pgmodeler.io/support/docs/44-connections-settings

If you already checked that connection to be the default for validation process maybe it's a bug.

About the validation, the SQL validation success is not mandatory to consider the model validation. There're two validation methods: 1) validation o the database model structure; 2) SQL validation, which executes the model's SQL in a server to check if the SQL is well constructed. The main purpose of the validation process is to create a well formed XML (.dbm) file in order to make it loadable in the next time the tool is open. See more here:

https://pgmodeler.io/support/docs/67-model-validation

**Comment by oliversalzburg** [comment]
Seems like I didn't look at the options properly yet again. Thanks a lot! I should check the docs more often...

**Comment by rkhaotix** [comment]
No problem! I'm here to help! :)
