### ISSUE TITLE
Rename column breaks data

### ISSUE THREAD

**Issue by jomu78** [pgmodeler/pgmodeler#1304]
When a column is renamed, this is not applied to inserted data. The data insert becomes invalid because the insert command still use the old column name. When opening the edit dialog the column is marked invalid but there is no easy way to fix this. 

**How to reproduce**

- Create table, name column test1 (not null)
- Edit data, use column name test1
- rename column to test2, open edit data --> column still named test1

Column in data dialog should be renamed automatically or at least there should be an easy way to select the new name of the column.

**Info about your desktop**
 - OS: Windows 7
 - pgModeler version: 0.9.2-beta
 - Qt version: 5.9.7

**Comment by rkhaotix** [comment]
In that case pgModeler you change the color of the column name in order to warn you that the column is not present anymore (see the image)

![data_edit](https://user-images.githubusercontent.com/2205476/62080218-9502c980-b226-11e9-992e-3b65626f6850.png)

As described in the warning box just double-click the column with red label and a popup menu will be displayed. Select the correct column name and click "Apply"
