### ISSUE TITLE
Wrong table creation SQL using PARTITIONING and ALTER statements

### ISSUE THREAD

**Issue by rbrdevs** [pgmodeler/pgmodeler#1337]
**Bug description**
SQL validation failed when using option "Generate ALTER for columns/constraints" and table partitioning.

**How to reproduce**

1. Create a table with one partition key. 
2. Enable "Generate ALTER for columns/constraints" option.
3. Open SQL source code visualizer and check that CREATE TABLE declaration is using partition key field before it exists.

```
CREATE TABLE points (
)
PARTITION BY RANGE (acquired_at);
```
` Message returned: `ERROR:  column "acquired_at" named in partition key does not exist`

**Info about your desktop**
 - OS: Windows
 - Version: 10
 - pgModeler version: 0.9.2-beta1

**Comment by rkhaotix** [comment]
Hmmm... I fear that the partition option can't be used together with "Generate ALTER..." this because a table can't but turned into a partitioned one after created... There's no way to issue a command like this `ALTER TABLE xxxx PARTITION BY RANGE(yyyy)`. 

Well... at least, is that the docs says: 
https://www.postgresql.org/docs/11/sql-altertable.html

**Comment by rbrdevs** [comment]
Ok, you're right, "Generate ALTER" option is not compatilbe with PARTITIONING. Maybe you could force table fields from partition key to be created in table CREATE statement.

I don't really need enabling this "Generate ALTER" option in my table setup, but one related issue I found is that using the "Export" tool seems to use always ALTER statements and fails on every execution. Even when model was successfully validated. Maybe It is related with this [issue ](https://github.com/pgmodeler/pgmodeler/issues/1302#issuecomment-541235564) and now It's fixed.
