### ISSUE TITLE
 Cannot find feature windows_vulkan_sdk

### ISSUE THREAD

**Issue by dgitc** [pgmodeler/pgmodeler#1346]
C:/msys64/mingw64/share/qt5/mkspecs/common/windows-vulkan.conf:1: Cannot find feature windows_vulkan_sdk

**Comment by titoshadow** [comment]
Warning, you can just ignore it

**Comment by jclive598** [comment]
got the same error, it wont make in the next step

**Comment by ams-tschoening** [comment]
Same error here and I think there's two different problems, with the first being that about the vulkan SDK and the second `g++` not being able to run by default. The following is a complete error message:

	$ /C/msys64/mingw64/bin/qmake -r CONFIG+=release PREFIX=/C/Users/tschoening/Documents/Repos/Git/GitHub/pgmodeler/pgmodeler/release pgmodeler.pro
	C:/msys64/mingw64/share/qt5/mkspecs/common/windows-vulkan.conf:1: Cannot find feature windows_vulkan_sdk
	Project ERROR: Cannot run compiler 'g++'. Output:
	===================
	===================
	Maybe you forgot to setup the environment?

The first thing is mentioned [elsewhere](https://github.com/msys2/MSYS2-packages/issues/1681#issuecomment-537188084) as well and should be [fixed](https://bugreports.qt.io/browse/QTBUG-76660) in newer versions of QT. Although I don't understand if there was a problem at all in the end.

The real problem why the build doesn't continue is because `g++` is not in `PATH` by default. After changing that, things continue, so that should be added to the installation docs. It might be necessary on Windows only:

    export PATH=$PATH:/C/msys64/mingw64/bin
