### ISSUE TITLE
Could not access the file or directory C:/conf/ui-style.conf! Make sure that it exists or if the user has access permissions on it!

### ISSUE THREAD

**Issue by BrendanMartin** [pgmodeler/pgmodeler#1353]
I'm using v0.9.2 on Windows 10 and I'm receiving this error when trying to start pgModeler from the command line.

Running this command in command prompt:
```start "pgModeler" "C:\Program Files\pgmodeler\pgmodeler.exe"```

Gives this error:
```Could not access the file or directory C:/conf/ui-style.conf! Make sure that it exists or if the user has access permissions on it!```

But running pgModeler normally by using the start menu shortcut doesn't cause this problem, it's only when launching from command prompt. 

It seems the file or directory it's trying to access is relative since when I moved pgModeler to C:/ it changed the message.

**Comment by rkhaotix** [comment]
On Windows, pgModeler should be executed by clicking directly its executable (or link at Desktop/Start Menu). In your case, it seems you'll need to wrap pgModeler's execution in a .bat script by initializing the needed environment variables before call the executable. This approach is used on packaged installation for Linux. 

I don't have experience in .bat scripts but you can follow the same direction as these ones:
https://github.com/pgmodeler/pgmodeler/blob/develop/pgmodeler.vars
https://github.com/pgmodeler/pgmodeler/blob/develop/start-pgmodeler.sh

**Comment by BrendanMartin** [comment]
Thanks for the info. As a workaround, I just changed directory to the pgmodeler.exe location before starting and it worked fine.

**Comment by BrendanMartin** [comment]
@rkhaotix It looks like I'm having a similar issue with pgmodeler-cli. When running something like:
`pgmodeler-cli -if schema.dbm -ef temp.sql`
I get the error:
```
I/O error : failed to load external entity "C:/Users/Brendan/Projects/conf/dtd/source-code-highlight.dtd"
ht SYSTEM "C:/Users/Brendan/Projects/conf/dtd/source-code-highlight.dtd"
                                                                               ^
validity error : Validation failed: no DTD found !
<source-code-highlight>
                      ^

[3] src/xmlparser.cpp (199)
  void XmlParser::readBuffer()
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Validation failed: no DTD found !.

[2] src/xmlparser.cpp (123)
  void XmlParser::loadXMLBuffer(const QString&)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Validation failed: no DTD found !.

[1] src/xmlparser.cpp (92)
  void XmlParser::loadXMLFile(const QString&)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Validation failed: no DTD found !.

[0] src/syntaxhighlighter.cpp (580)
  void SyntaxHighlighter::loadConfiguration(const QString&)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Validation failed: no DTD found !.

** pgmodeler-cli aborted due to critical error(s). **
```

**Comment by ams-tschoening** [comment]
You should try to get rid of the environment variables and replace accessing those with some code in pgModeler simply doing the calculations done by the script on Linux or the installer on Windows settings those variables. Assuming a relative directory tree based on the installation dir of your app totally makes sense and with that assumption you can simply calculate all necessary paths on runtime.

That's what actually is done using double-clicking in Windows, the current directory is simply set properly in that case already. That fails in case one clicks a `*.dbm` file, because the current directory is that of the `*.dbm` file in that case and that's why you need your environment variables. But because your current QT-based installer only installs per user, see #1349 and #1350 for details, those are not available by default and things break again. If you would calculate the required paths on runtime instead of querying environment variables, pgModeler would at least work even without proper start menu entries for all users.

Alternatively, using a start-up script like is done for Linux might work as well. But adding it only once in the code base for all platforms should be the easier approach in the long term. The following is a PoC for such a script:

[pgModeler.txt](https://github.com/pgmodeler/pgmodeler/files/4007044/pgModeler.txt)
