### ISSUE TITLE
Goes non-responsive on import (reverse engineer)

### ISSUE THREAD

**Issue by hart7274** [pgmodeler/pgmodeler#1405]
I have tried using the 2 most current versions with the same results. If I try and use the import option, I will eventually lock up without completion. We have a rather large database. As soon as I select my database, it starts going through the list of tables. If I try to switch to another screen to work on something else while it works, or if I my windows device locks the screen, the process freezes and becomes non-responsive. It will never resume where it left off. I have tried to just let it finish and keep my mouse moving so that windows will not lock my session, but after 1.5 hours, it was 80% and I had to move on to something else. I do not have 2 hours to just sit and move my mouse waiting and hoping it finishes. I need to move to other things while it finishes processing. I need it to not lock up when it isn't the screen in focus.

**Comment by rkhaotix** [comment]
Which OS?
PostgreSQL version?
Qt version?
Did you compiled pgModeler?
Can you provide a dump of your database so I can debug the import operation?

**Comment by hart7274** [comment]
Windows 10
Postgres 9.6.11
I bought the compiled version of pgModeler.
I have to check with someone above my pay grade on whether I can get you a dump of our database.

**Comment by i-love-coffee-i-love-tea** [comment]
Hi!

You said you have a large database. How many tables do you have? Is it
a slow connection? I'm curious, because I have a database schema
which I'd describe as large, with 150 tables, 250 relations. It
doesn't fit on my 4k display. Everything takes only around 30
seconds to create on my local db server.

Out of the blue...
Do you have a stable network connection to the server? Over an hour
seems strange to me, if you aren't running some data preparation
procedures?


Regards

Steffen

**Comment by rkhaotix** [comment]
@hart7274 Thanks! 

Try to adjust the verbosity of the import process in settings. The majority of times the process hangs due to the amount of UI operations that need to be performed. Reducing the verbosity helps a lot and you can get your db imported.

You have another option to import the database which is to use pgmodeler-cli for that matter.
https://pgmodeler.io/support/docs/613-command-line-interface?v=0.9.2

**Comment by hart7274** [comment]
By large, we are talking tens of thousands of tables. 

Changing the verbosity didn't help at all. It still locked up.

I'm running pgmodeler-cli now and it is progressing while allowing me to continue to work on other things.

Ideally, I do not want all the tables to pull into the model. I only need a few, but cannot select just those few that are needed to join in with the new tables I'm creating.

**Comment by rkhaotix** [comment]
Oh, ten of thousands are something that I'm certain that pgModeler can't handle at once! You have to work on a subset of this enormous database. But I wonder why you can't select the objects before import? Can you explain a bit more this part?

**Comment by hart7274** [comment]
I click the import button on the left. This displays the import database dialog. I select my connection. I do not have any options at this point to chose any specific tables I want to import. I have to select the database first. When I select the database, it displays the popup  with scrolling "Retrieving objects of".... where it shows which tables it is processing. This is where it will lock up as soon as I click away. Giving it back focus results in Windows telling me it is not responding. I have left it on this display for a long amount of time, but it never recovers or finishes. I won't be able to select which tables to import until after this process has finished.

**Comment by rkhaotix** [comment]
Hm... So it hangs during the objects listing... 
I think I will really  need a dump of the database to get into this issue. This is new to me.

**Comment by i-love-coffee-i-love-tea** [comment]
Hi Raphael,

i did some testing with 20000 empty tables, just for the fun of it.
Before opening the import view, I enabled low verbosity mode in the
settings.

What i noticed is, in the import dialog the objects load very
slow after selecting the database. It took around an hour to load
10000 tables (where it updates the status text "Retrieving objects of
`%1' (%2)..."). This is before selecting the objects to import, to be
clear. Interestingly the database objects tree in the database
management view loads without noticeable delay.

Just by looking at the code, with my limited qt experience, I was unable
to identify the lines which cause the long wait. My profiling attempts
weren't successful until now. (I'm struggeling with setting up the
profiling build. QtCreator runs the build, but says it can't find
-lpgconnector and others.)


Regards
Steffen

**Comment by rkhaotix** [comment]
Interesting @i-love-coffee-i-love-tea ! 
It seems that the bottleneck is in the object names retrieving. I'll start from there...

About your problems compiling pgModeler, make sure to disable shadow build so it can find all the libraries correctly.

**Comment by rkhaotix** [comment]
@i-love-coffee-i-love-tea @hart7274 I found it! The problem is that the tree is getting sorted everytime a table (or any other object) is retrieved from the database. In Qt sorting tree items is very time consuming.  And that sorting shouldn't happen there!

I was affraid that it could be some problems on the catalog queries but it seems they're ok. I'll mark this issue as enhancement and provide the fixes for the next release 0.9.3.

@i-love-coffee-i-love-tea you can test the speed gain on your side (after compiling pgModeler) by commenting the line 879 ```tree_wgt->sortItems(sort_by, Qt::AscendingOrder);``` in the method ```DatabaseImpotForm::updateObjectsTree()``` in the file ```databaseimportform.cpp```. After commenting that line the process took nothing more than 3 minutes to list the same 20000 tables you tested.

**Comment by hart7274** [comment]
Thanks. For now, I've cloned my DB and removed a ton of tables that I know I'll never need to import so that I can continue working. I appreciate your efforts here.

**Comment by rkhaotix** [comment]
Ok guys, after the commit 5e77354 I was able to list 20000 tables quickly and select them for importing. Despite that, the reverse engineering suffers from performance degradation proportionally to the number of objects to be imported (as I always expected). I'll fix things little by little... the reverse engineering is a complex process and needs caution when performing code optimizations. 

But to be honest, I don't think using pgModeler to import a large database and handle everything altogether will work properly... As the original issue from @hart7274 handling tens of thousand objects in a single canvas is impractical IMHO (I don't even imagine how this can be done in a graphical tool). The patch I'll provide for this issue is just to minimize the slowdowns/hangups allowing the user to choose the subset of objects to work on.

**Comment by i-love-coffee-i-love-tea** [comment]
As far as I'm concerned, I'm happy with the sorting fix. I was
able to list the 20000 tables in 3 minutes, but now the import process
is running for more than four hours. But I agree about the practicality.
I was only curious and it didn't take much time to test it.

Thank you for the tip to disable shadow build. :)

**Comment by Maxzor** [comment]
About improving big models graphically, I have one idea in mind after playing with KDAB's Gammaray : crow foot notation is taking a giganormous CPU load, there might be a substantial improvement reservoir there.

**Comment by rkhaotix** [comment]
@Maxzor not only that but you have a point here. Crow's Foot notation uses lots of lines to represent the relationship. Theses objects was the only ones I did not touch when doing the graphical objects polishing! 

But even improving relationships (which can give a lot of headache but the result should be satisfactory) one problem persists: the canvas was not designed to display tons of tables and relationships. This can be solved by implementing the model splitting in different canvas allowing the user to load a huge model files and separate the model in different tabs (which intercommunicate between themselves). This is a complex work but inevitable in some point in the tool's development timeline!
