### ISSUE TITLE
Make extension available when selecting function for trigger

### ISSUE THREAD

**Issue by kuz30** [pgmodeler/pgmodeler#1422]
**Feature description**
Make extension available when selecting function for trigger

**Additional info**
Right now you can select only schema functions when creating table trigger
But there is useful extension `moddatetime` that can be globally used for triggers

**Comment by rkhaotix** [comment]
Making pgModeler keep any extensions objects offered by PostgreSQL as built-in objects adds unnecessary complexity to its maintenance. 

For your case I think that a mix of manually cresting the extension and some dummy objects solves your problem:
https://pgmodeler.io/support/docs/714-creating-dummy-objects?v=0.9.2

My advice for, create the extension which holds the ```moddatetime``` trigger. Then create a dummy function called ```moddatetime``` and use it on your custom triggers.

**Comment by kuz30** [comment]
Trying to follow the advice, but getting few issues:
- how to pass column to trigger?
- how to get rid of schema definition ahead dummy function?

`
-- object: mdt_token | type: TRIGGER --
-- DROP TRIGGER IF EXISTS mdt_token ON ad.token CASCADE;
CREATE TRIGGER mdt_token
	BEFORE UPDATE OF updated_at
	ON ad.token
	FOR EACH STATEMENT
	EXECUTE PROCEDURE ad.moddatetime();
`

**Comment by kuz30** [comment]
Desired generated code from Postgres example: https://github.com/postgres/postgres/blob/master/contrib/spi/moddatetime.example

**Comment by rkhaotix** [comment]
1) In order to pass the column to the function use the tab ```Arguments``` on the trigger's editing form.
2) You can't remove the schema name from the function's signature in the trigger's defintion. Not by usual ways. You can edit the generated code after exporting it to a SQL script. But, you can create the function in the same schema as the extension ```moddatetime``` is installed so the function can be called correctly.

See my sample model I could reproduce the SQL code as you exemplified:
[moddatetime_example.zip](https://github.com/pgmodeler/pgmodeler/files/4533024/moddatetime_example.zip)

**Comment by kuz30** [comment]
Appreciate you example, it helps!
In my case I guess it wold be better to move such triggers in custom SQL due to multiple schemas using moddatetime.
