### ISSUE TITLE
Incorrectly prohibits partition on primary key created by fk relationship (v.12)

### ISSUE THREAD

**Issue by washad** [pgmodeler/pgmodeler#1474]
According to this; [https://pgdash.io/blog/partition-postgres-11.html](pgdash) and my current working example, PostgreSQL 11+ supports using a foreign key as a partition key. However, pgModeler still gives the following error on creation; 

![image](https://user-images.githubusercontent.com/11013124/93259676-6f53bf00-f75d-11ea-8e9e-c712cc48f389.png)

The only work around I can find is to add custom SQL that drops the table then re-creates correctly. However, if someone later changes the table without knowing the work-around, the changes will not work. Also, I cannot then properly model the partitioned tables. 

SteveJ

**Comment by rkhaotix** [comment]
@washad This error is raised because you're trying to create a partition key using a column that was created by a relationship (one-to-one or one-to-many). I'll not enter in technical details but pgModeler does not support this operation yet. But you can use any other column in a partiontion key even the ones representing a foreign key(see the image below).

![part_key_sample](https://user-images.githubusercontent.com/2205476/93274195-25d09780-f790-11ea-9c35-740eb79dd79f.png)

Here we have two tables named ```partioned_a``` and ```partitioned_b```, if you notice they are *almost* the same, despite the fact that ```partitioned_a``` has a foreign key column ```id_reftable``` which was automatically created by the relationship ```reftable_has_many_partition_a```, the same is valid for the constraint named ```reftable_fk``` (read [here](https://pgmodeler.io/support/docs/310-relationships?v=0.9.2) to understand the column/constraint propagation mechanism). That column is the root of the problem you're facing. It can't be used in the partition key.

The workaround for this problem is implemented by the table ```partition_b```. In this case, the link between ```partitioned_b``` and ```reftable``` was manually created by me using a foreign key object named ```reftable_fk_cp``` that is composed by the column ```id_reftable``` which was also added manually. Now, if you try to create a partition key using that column you'll see that it actually works.

You can try yourself by using the attached model:
[part_key_test.dbm.zip](https://github.com/pgmodeler/pgmodeler/files/5228695/part_key_test.dbm.zip)

**Comment by washad** [comment]
I was able to make it work using the prescribed approach. Thank you. If you are ever in the SLC Utah area hit me up and I'll buy you that coffee!

Cheers.
