### ISSUE TITLE
Diff does not handle well regexp on domain type

### ISSUE THREAD

**Issue by FGRibreau** [pgmodeler/pgmodeler#1497]
**Bug description**

When a domain has a regexp constraint, e.g.:

```sql
create domain public.my_type as varchar(64) check (value ~* '^(([a-z]|[a-z][a-z0-9\s\-]*[a-z0-9])){3,64}$');
```

The diff tool always output this domain like it changed when it did not.

**How to reproduce**

Use pgmodeler (v0.9.3) diffing feature against 2 databases that have this domain. 

**Expected behavior**

No diff output. Since this domain exist in both database, pgmodeler diff should output nothing.

**What happened**

```sql
ALTER DOMAIN public.my_type DROP CONSTRAINT public.my_type_check;
-- ddl-end --
ALTER DOMAIN public.my_type ADD CONSTRAINT public.my_type_check CHECK (((VALUE)::text ~* '^(([a-z]|[a-z][a-z0-9\\s\\-]*[a-z0-9])){3,128}$'::text));
-- ddl-end --
```

**Info about your desktop**
 - OS: Linux & Mac
 - pgModeler version: 0.9.3-beta1

We are willing to pay to prioritize this bug fix 🙏  along with https://github.com/pgmodeler/pgmodeler/issues/1488 :)

**Comment by rkhaotix** [comment]
I'm aware of this...

Unfortunately, this is a hard one because once you execute the ```create domain``` PostgreSQL parses the command and stores the object in the system catalogs. 

When one tries to retrieve the domain from the catalogs, PostgreSQL returns the reconstructed command, semantically equals to the original one, but never the one executed by the user.

Due to this behavior, the diff will always detect differences between the objects, even if they semantically equal.

AFAIK, PostgreSQL doesn't store the original command, which could help to solve this problem easily. An alternative solution would be a SQL semantics analyzer, which can be a lot complicated to implement.

**Comment by FGRibreau** [comment]
In our case we are comparing two database together, so both have the same parsed object.

Why don't we compare both parsed command to see if they match? Its some kind of AST right?

**Comment by rkhaotix** [comment]
Hmmm... Are you comparing two databases? I thought you were comparing a model and a database. Now, this changes the conversation a little bit... Theoretically, the comparison between equal domains directly from the database shouldn't be resulting in diff code. I'll try to investigate this then.

**Comment by FGRibreau** [comment]
YES! 🎉

![giphy](https://user-images.githubusercontent.com/138050/100107695-383f0f80-2e6a-11eb-8103-91632ae39026.gif)

**Comment by rkhaotix** [comment]
Well, the process has worked as expected...  the diff doesn't generate any code.

See here: 
https://www.youtube.com/watch?v=YD-wjRH7jc4

**Comment by FGRibreau** [comment]
Hum, I could not reproduce it either, I will reopen it when we find another case :)
