### ISSUE TITLE
Custom SQL is not inspected to generate the DB diff.

### ISSUE THREAD

**Issue by AntonioAngelino** [pgmodeler/pgmodeler#1500]
**Bug description**
I need to add comments on FK fields. Since the fields linked to a relationship are frozen, I had to do it via Custom SQL.
The Export tool works as expected and appends my custom SQL, but the diff tool doesn't care about custom SQL and generates a wrong diff.

**How to reproduce**
1. Create two tables.
2. Create a one-to-one or a one-to-many relation between the tables
3. Add a comment for the FK field via Custom SQL.
4. Run the diff tool.

**Expected behavior**
The diff tool should inspect the custom SQL code and generate the diff accordingly.

**Info about your desktop**
 - OS: Windows
 - Version: 10
 - pgModeler version: 0.9.3-beta1

**Comment by rkhaotix** [comment]
The diff ignores any custom SQL code, this is by design.

If you need to edit the comments on generated FK you can convert the relationship which generated it causing the unlockin of the constraint and, consequently, allowing the handling of any attribute of that object.

See more here:
https://pgmodeler.io/blog/2020/5/20/pgmodeler-093-alpha1-is-out-of-the-oven

**Comment by AntonioAngelino** [comment]
Great! Thank you @rkhaotix for the quick reply! 👍
