### ISSUE TITLE
create Gin Index with gin_trgm_ops on pg_trgm extension get syntax error 

### ISSUE THREAD

**Issue by hiepxanh** [pgmodeler/pgmodeler#1537]
I want to create an Gin Index by using pg_trgm extension
I create a index like this: 
![image](https://user-images.githubusercontent.com/16970990/115861787-6fd3d700-a45d-11eb-8908-7c25f794a95f.png)

getting this in the SQL code:
![image](https://user-images.githubusercontent.com/16970990/115861760-621e5180-a45d-11eb-9174-cf4b0b64bfc6.png)

then I diff to apply to server:

![image](https://user-images.githubusercontent.com/16970990/115862684-a100d700-a45e-11eb-80db-ade3b4f1e6cd.png)

get error while export

I see an issue like this: https://github.com/pgmodeler/pgmodeler/issues/852
but it not really solve the problem, I would like to have a feature like checkbox that allow us to remove not necessary parenthesis as an official workaround 

# expect
I expect to have checkbox button to remove parenthesis, or some solution to workaround  @rkhaotix 

love to hear you

**Comment by hiepxanh** [comment]
https://drive.google.com/file/d/1cJlyYRYl7hSHCGxuPA-0M_elFUlboy-d/view?usp=sharing
here is the database you can review it @rkhaotix  If you dont mind, can you get a little view? to help me solve that problem?
since the application change the operator class, I dont know how to add it to my case

**Comment by rkhaotix** [comment]
Hi @hiepxanh !

This problem is easy to solve... Here's the steps you have to do in your database model:

1) Create the ```pg_trgm``` extension in any schema of your choice.

2) Create a dummy operator class called ```gin_trgm_ops```, just make sure that the operator class resides in the same schema as your ```pg_trgm```. The dummy operator class can be configured like the image below:

![example_gin_trgm_ops](https://user-images.githubusercontent.com/2205476/115866885-b8b16e80-a410-11eb-99e2-87cee437d998.png)

3) In your ```title_gin_idx``` on table ```public.books``` delete the expression element and add a new one with the following configuration:

![example_idx_element](https://user-images.githubusercontent.com/2205476/115867147-15148e00-a411-11eb-9aa2-c7d9cf29bf9c.png)

And here's the model with all those objects created: 
[gin_index_test_db.zip](https://github.com/pgmodeler/pgmodeler/files/6365035/gin_index_test_db.zip)

**Comment by hiepxanh** [comment]
wow, you reply very fast, thank you so much, I already test with your solution, if I click from 1,2,3,4, then 5, it display like this, I already check but I dont know what did I wrong,
![image](https://user-images.githubusercontent.com/16970990/115943550-b6b3e200-a4da-11eb-8409-1ae585f36800.png)

if i click on storage, it work without any issues, so strange @rkhaotix 

![image](https://user-images.githubusercontent.com/16970990/115943565-d77c3780-a4da-11eb-8156-e5fff966342f.png)

**Comment by hiepxanh** [comment]
BTW, using storage is very good, problem solved.
 I have two question?
1) is that "assignment of not allocated object!" warning is correct or not? I think it should work
2) using storage is still work fine with my case. is that any problem if I using "storage" instead of "operator"

Thank you so  much to help me. It's worked. 

Should we update this to docs example on this page? 
https://pgmodeler.io/support/docs/34-indexes?v=0.9.3

**Comment by imShara** [comment]
Tried  @hiepxanh method, but getting validation error:
```
The object public.gin_trgm_ops (Operator Class) [id: 5150] is being referenced by 1 object(s) before its creation.
```

When I press "Apply Fixes", progress falls into infinite loop

**Comment by imShara** [comment]
Possible workaround is "save anyway" and fix schema on re-open in pgModeler.
