### ISSUE TITLE
Fillfactor

### ISSUE THREAD

**Issue by babs** [pgmodeler/pgmodeler#157]
Hello,

It would be interesting to have the fill factor box set to empty be default to avoid FILLFACTOR definition at export to let the postgresql use the most optimal one (depending of index type).

For example, according the documentation, default FILLFACTOR for B-Tree is 90 (10 seems to be a BAD idea in this case :) ).
http://www.postgresql.org/docs/9.1/static/sql-createindex.html

Regards,
D.

**Comment by ams-tschoening** [comment]
I'm using version 0.9.1 and came across the same problem with `fillfactor`, that some constraints used very low values like `10` while others used higher values like `100`. This was most likely because of different default values or alike, because I can't remember having set such values explicitly in the past. Instead, I do prefer Postgres defaults as well.

So I removed all those values from the underlying XML file, as those were easier to find there instead of checking everything manually in the UI. After loading the schema, pgModeler failed, because it said that it requires `factor` for indexes. I let it fix the model and recognized that it added attributes `factor="0"` for indexes again. Though, when looking into the GUI for those indexes, the checkbox for the fill factor is NOT checked and contains a disabled value of `90`. So this most likely means that an attribute of `factor="0"` in the XML means to not set one explicitly and in fact, NO fill factor is rendered in the SQL for indexes. Just like I want.

Though, is there any reason to NOT require/render such attribute for constraints while DO requiring it for indexes? In my opinion it would be less confusing if it simply would not be required when not checked in both cases.
