### ISSUE TITLE
Modifying composite primary key is not "diff"ed correctly

### ISSUE THREAD

**Issue by Ileca** [pgmodeler/pgmodeler#1597]
**Steps to reproduce:**
Create a table with three columns aaa, bbb, ccc, and a composite primary key on the first two aaa-bbb columns.
Apply that to your db.
Modify the primary key by adding the third column ccc to it.
Diff.

> ALTER TABLE public.test ALTER COLUMN ccc SET NOT NULL;

This is obviously not the expected result. Once it is applied, any diff considers that there is no difference anymore.

I have a fresh install of pgmodeler and a new database. Also, my diff uses PG 11.0.

**Comment by rkhaotix** [comment]
This IS the expected rresult, in pgModeler's perspective. The tool can't change the columns of a primary key because there's is no such command in PostgreSQL. You have to force the recreation of the constraints to get the desired results. See more here:

https://pgmodeler.io/support/docs/53-compare-model-and-database?v=0.9.3

**Comment by Ileca** [comment]
> Instead of using an ALTER command to modify certain kinds of objects a DROP and CREATE will be used in order to do a full modification. This option does not affect the database object.
But when it comes to renaming a column, pgModeler drops the column (or the table) and all the data in it before recreating it, even though there is a simple alter command for that. (Pretty dangerous if you ask me.)
It is the same if I rename my primary key, the key is dropped and recreated. Why, by your logic, is this possible? Why can't this primary key be dropped and recreated the same way, but this time to change its definition?

I am not sure I follow you here.

Shouldn't there at least be some kind of notice that the model and the DB are not 100% matching each other and maybe what are these differences. As of now, you have to guess what pgModeler can handle or not, if you don't use the option to force changes, and can't say for sure, if you do a lot of modifications to the model, if the model and the DB are properly synchronized.

**Comment by rkhaotix** [comment]
> But when it comes to renaming a column, pgModeler drops the column (or the table) and all the data in it before recreating it, even though there is a simple alter command for that. (Pretty dangerous if you ask me.)

I never said that the diff is safe! I don't even recommend running it on production servers without having a backup in the first place. The diff feature is still **experimental** :)

> It is the same if I rename my primary key, the key is dropped and recreated. Why, by your logic, is this possible? Why can't this primary key be dropped and recreated the same way, but this time to change its definition?

pgModeler also can't resolve objects' renaming as stated in the docs. If you notice, there are also two options to control the generation of drop objects that can minimize these problems.

> Shouldn't there at least be some kind of notice that the model and the DB are not 100% matching each other and maybe what are these differences.

This one is part of a future patch that I'm planning to do.

> As of now, you have to guess what pgModeler can handle or not, if you don't use the option to force changes, and can't say for sure, if you do a lot of modifications to the model if the model and the DB are properly synchronized.

pgModeler can't handle properly objects that don't accept ALTER commands for modifications, that's why we have some workaround to try to simulate the changes detection and applying. That's the case for _aggregate_, _cast_, _constraint_, _collation_, _conversion_, _language_, _operator_, _operator class_, _operator family_, _rule_, _trigger_, and _view_. 

Since they are workaround solutions, there's no 100% grantee that they will detect/generate all the needed code to make the model and DB synchronized.

**Comment by Ileca** [comment]
Sorry for the late reply. Long story short, my PC broke. I am glad pgModeler is also on Linux!
Anyway, thanks for the explanation. I understand that I should stay away from the diff feature until it's more mature. Still pretty useful to generate ready to go code you can cherry pick manually to synchronize your db.
Now I close that issue because I think you have already way too many to take care of. Keep up the good work!
