### ISSUE TITLE
Questions about source code pgmodeler 0.9.3 stable.  ???

### ISSUE THREAD

**Issue by PowerUser1234** [pgmodeler/pgmodeler#1602]
I have successfully built pgmodeler 0.9.3 stable on Windows 10 64 bit, from the official online instructions, a little help, and a little initiative.

-Is my build version of the program 32 bit, or 64 bit, software?

-Does my pgmodeler program have a query builder by default, or otherwise?  Is there a plugin that I can obtain for free to gain this? If so, where and how?

-I am curious to know if pgmodler has, either by default or an available plugin, a "code builder" with "code templating", syntax injection, on top of code completion, the way that DBeaver has?  Not just for query building, but for any PostgreSQL programming, such as development of Triggers, as only one example? If this doesn't exist in a default stable source code build, is there a plugin I can obtain to gain that, for free? Where, and how, kindly, please?

-At an estimate, how far away is the stabe version of pgmodeler v0.9.4?  Particularly, its source code bundle release, to the world, online?

**Comment by rkhaotix** [comment]
> -Is my build version of the program 32 bit, or 64 bit, software?

If you followed the instructions, I'm 99.9% sure that it is 64 bits!

> -Does my pgmodeler program have a query builder by default, or otherwise? Is there a plugin that I can obtain for free to gain this? If so, where and how?

Yes, there's an experimental plugin for query building:
https://github.com/pgmodeler/plugins/tree/master/graphicalquerybuilder

> -I am curious to know if pgmodler has, either by default or an available plugin, a "code builder" with "code templating", syntax injection, on top of code completion, the way that DBeaver has? Not just for query building, but for any PostgreSQL programming, such as development of Triggers, as only one example? If this doesn't exist in a default stable source code build, is there a plugin I can obtain to gain that, for free? Where, and how, kindly, please?

Are you talking about code snippets? 
https://www.pgmodeler.io/support/docs/45-snippets-settings?v=0.9.3

> -At an estimate, how far away is the stabe version of pgmodeler v0.9.4? Particularly, its source code bundle release, to the world, online?

Until the end of December I want to release the stable 0.9.4

**Comment by PowerUser1234** [comment]
Dear Raphael,

thank you for your awesome pgmodeler.  All of these answers are the best new I could hope for.

-Where in 0.93 stable do I go to see and start using code snippets?  Does pgmodeler
have code snippets for fairly well all the database objects of PostgreSQL?

-It seems as though building the query modeler needs to be done when building pgmodeler.
I am running Windows 10 64 bit.  Is there any way to build the Query Builder plugin
on its own, so that the result can just be pasted into the root directory of pgmodeler?

-Will the query modeler be included by default in 0.9.4?  How far away is the query modeler
from being stable software?

Many Thanks, as usual!  Merry Christmas!

**Comment by rkhaotix** [comment]
> -Where in 0.93 stable do I go to see and start using code snippets? Does pgmodeler
have code snippets for fairly well all the database objects of PostgreSQL?

You can use code snippets in any source code input field. 

https://pgmodeler.io/support/docs/25-source-code-input-fields?v=0.9.3
https://pgmodeler.io/support/docs/24-code-completion-widget?v=0.9.3

And to configure them, as I said previously, you can use the snippets editor:
https://www.pgmodeler.io/support/docs/45-snippets-settings?v=0.9.3

> -It seems as though building the query modeler needs to be done when building pgmodeler.
I am running Windows 10 64 bit. Is there any way to build the Query Builder plugin
on its own, so that the result can just be pasted into the root directory of pgmodeler?

For now, you have to build the plugin together with pgModeler itself. I'll work on an improvement in the build to allow compiling the plugins without the need to compile pgModeler too.

> -Will the query modeler be included by default in 0.9.4? How far away is the query modeler
from being stable software?

The query builder plugin is not stable enough to be included in  0.9.4 by default.

> Many Thanks, as usual! Merry Christmas!

No problem! Merry Christmas to you and your family too!

**Comment by PowerUser1234** [comment]
-Ask a silly question, but how do I get the snippets editor to come up?

-And whereabouts can I get to see a "source code input field"?
