### ISSUE TITLE
Bad constraint comment SQL generated.

### ISSUE THREAD

**Issue by tanzanite777** [pgmodeler/pgmodeler#1868]
**Bug description**
The following invalid SQL got generated:
```
COMMENT ON CONSTRAINT fwo_lang_entry_key_chk ON  IS E'Only ASCII lower/uppercase letters and ''_'' is accepted';
```
ERROR: syntax error at or near "IS"

**How to reproduce**
Make a CHECK constraint with comment and generate SQL for it via diff.

**Expected behavior**
Valid SQL.

**Info about your desktop**
 - pgModeler version: 1.1.0
 - SQL version: PostgreSQL 16.2

**Comment by rkhaotix** [comment]
I didn't test it but I suspect that the error is happening because you are using the escaped string `E'...'` , see here:

https://www.postgresql.org/docs/16/sql-syntax-lexical.html

I think you have to replace the `''_''` by `\'_\'`. The escaped string in comments is the default behavior but it can be toggled in general settings.
