### ISSUE TITLE
Make primary keys easier to set

### ISSUE THREAD

**Issue by scottsd** [pgmodeler/pgmodeler#258]
Not sure if I got this right, but to create a PK one has to
1. go to Constraints
2. new
3. type a name (unique for each table)
4. select and add one or more columns

It would be easier if one could check a box when editing columns, [x] Primary Key. This is similar to how Dia DB modeller works. 
Generated code shouldn't include any name:

```
CREATE TABLE example (
    a integer,
    b integer,
    c integer,
    PRIMARY KEY (a, c)
);
```

**Comment by buildbotter** [comment]
Kind of crazy that a basic feature for a data modeler is so silly to create primary keys, when every other data modeler is perfectly fine to create primary keys.... so many hoops to jump through when creating tables!

I had to google to find how to create primary keys, which is bad UX as this is one of the first things users will try to do.

What can we do to help create this feature? I would love for this to be added.

**Comment by joshuataylor** [comment]
Kind of crazy that a basic feature for a data modeler is so silly to create primary keys, when every other data modeler is perfectly fine to create primary keys.... so many hoops to jump through when creating tables!

I had to google to find how to create primary keys, which is bad UX as this is one of the first things users will try to do.

What can we do to help create this feature? I would love for this to be added.

**Comment by rkhaotix** [comment]
> Kind of crazy that a basic feature for a data modeler is so silly to
create primary keys, when every other data modeler is perfectly fine to
create primary keys.... so many hoops to jump through when creating tables!

Ok, other Modeler tools are far away mature compared to pgModeler. I'm
working every day to improve the user experience in every release.
Unfortunately some features seem easy to implement to the user's eye but
the code base need some adjustments that take some time!

> I had to google to find how to create primary keys, which is bad UX as
this is one of the first things users will try to do.

I'm not an UX expert and I know that pgModeler lacks a simple way to create
pks which is being planned to be included in next releases 0.8.2 or 0.9.0

> What can we do to help create this feature? I would love for this to be
added.

The only thing I ask is patience! I have the clear idea on how to add this
feature but my time is a bit reduce and because of this I'm focusing in bug
fixes. If you know Qt and C++ just fork the project, make the changes and
submit a pull request.

**Comment by tschoening** [comment]
> Kind of crazy

Calm down...

> that a basic feature for a data modeler is so silly to create primary keys, when every other data modeler is perfectly fine to create primary keys....

So why don't you use any of the other modelers then?

> I had to google to find how to create primary keys[...]

I don't and as I said before, there are good reasons to force devs to manually create primary keys as well.

> What can we do to help create this feature? I would love for this to be added.

Patches are always welcome.

**Comment by joshuataylor** [comment]
I didn't mean to start a flamewar, I love pgmodeler (I even donated for the 'gold' version).

**Comment by rkhaotix** [comment]
It's OK Josh. Your comment sounds a bit harsh but I understand your desire
to have a "simple" feature like that. Soon or later this option will
available in pgModeler! 😁

P.S.: Thanks for the donation!
Em 14/06/2015 16:45, "Josh Taylor" <notifications@github.com> escreveu:

**Comment by auroraeosrose** [comment]
Some opinions on the subject

Postgresql has slightly different behaviors for named vs. not-named constraints - not when running but definitely on creation

The biggest reason to have a checkbox is for people who DO rely on the automatic postgresql naming/indexing behavior for primary keys and other "generated" style constraints - a "checkbox" generated primary key SHOULD generate different sql than a "constraint" generated named primary key

documentation is here for the behavioral differences -  http://www.postgresql.org/docs/current/static/sql-altertable.html 

so for alter/create table the primary key checkbox should generate

ALTER TABLE example  ADD PRIMARY KEY(a)

where the fully named constraint version should be generating sql as

ALTER TABLE example ADD CONSTRAINT my_explicit_constraint_name PRIMARY KEY (a)

an alternative that would help with people who are confused about naming constraints (since postgresql WILL magically generate them for you) would be to make naming constraints optional and simply generate them identically to the way postgresql does it 

see http://stackoverflow.com/questions/4107915/postgresql-default-constraint-names for some information on the subject

**Comment by tschoening** [comment]
The automatically generated names are an implementation detail and nowhere in the official docs is documented that one can rely on them or how stable they are. So while it may be OK to generate different SQL with and without explicit constraint names, pgModeler shouldn't generate any names itself which one might think of would be the names Postgres would have generate instead. It's simply the wrong approach for people who most likely already doing something wrong... ;-)

**Comment by rkhaotix** [comment]
I agree with @tschoening 

There is no problem in doing automatic constraint naming in pgModeler but in order to make other operations like reverse engineering, export and diff work properly we NEED to assign a name to any object handled by pgModeler. So, optional names are out of question.

pgModeler can handle the generation of names easily but we'll only being transferring the responsibility to create objects' names from PostgreSQL to pgModeler, which will be implementation specific since there is no gold rule for that purpose.

**Comment by anseljh** [comment]
Just wanted to say that I agree wholeheartedly that this would be a **huge** improvement. I was stumped about how to create a primary key until I found this GitHub issue. Thanks!
