### ISSUE TITLE
Refresh schema / See difference between real database and model

### ISSUE THREAD

**Issue by kvonmurphy** [pgmodeler/pgmodeler#393]
I can easily reverse engineer a database. But how to refresh this model with modifications that may have been done directly with SQL? How to compare my schema done from the prod database with the schema on the development server? How to know at first sight the difference what will be contained in my update script ?

That would be nice: a "Compare" button would search the same objects in the database, flag (other color, icon, italic...) what has changed, add (with flags) what is in the database and not in the model.  You could hide these differences with a checkbox in the toolbar.

If performance permits, a background process would scan the database from time to time and update the screen. 

The Compare window could list all differences, with possibility to commit them, but I would prefer to see them directly in the model and accept them one by one.

**Comment by davidkuep** [comment]
Hi I just downloaded version 0.8.1 and it seems this feature still isn't there, what's the status? It would be incredibly helpful for me.

**Comment by ieugen** [comment]
Hello, 

I also need this feature. 

I imported the database schem and worked for 1-2h on it to pull tables and relationships so they are easy to read. 

The resulted diagram helped me to identify improvements and it was valuable. I've applyed those sql migrations in my application (using flywaydb as part of a Java application ) and now I found out I can't refresh the design diagram to update the missing relationships. 

The only way I can have it is by loosing all the work I did so far in arranging the tables and redo that work by hand. As you can imagine, this is not very productive and I don't have any incentive to do it since it doesn't bring value. 

Plaease condider adding a 'Refresh' option that syncs a design to a database by adding new relations to the desing model and optionaly removing missing relations. 

The operation should keep existing postions of relations/tables in the design window. 

Thanks,

**Comment by rkhaotix** [comment]
@ieugen Which version you're using?

I've introduced a small workaround until I have time to implement the real sync between database and the model. In 0.8.2-beta1 you can extract metadata from the objects of a given model and apply it to another. In practice, you can copy the table's postions, relationship points, custom colors, tags, textboxes and paste in another one in order to restore a previous configuration.

This feature was created aiming exactly the problem you mentioned. So, what you have to do is:

1) Open the original model (the outdated one).
2) Open the metadata handling dialog (see picture below) and choose 'Save metadata file'. Select the output file and click 'Apply'. I recommed leave all options checked. The method will create a xml based file with the extension .omf (objects metadata file).
3) Import the database you want to apply the metadata.
4) Open the metadata handling dialog again with the imported model focused and now choose 'Load metadata file', select the input file (the one generated in step 2) and click 'Apply'.
5) You now have all objects belonging to the old model in their original positions. Now what you have to do is to configure the positions of the objects that are missing in the old model (the ones created directly in the database).

Hope it can help you.

![handle_metada](https://cloud.githubusercontent.com/assets/2205476/14820409/f025060e-0b9c-11e6-8941-b4ab8ad73253.png)

**Comment by ieugen** [comment]
Thank you. It works well enough. It's a bit cumbersome to use but I'm happy. 
 
If you make it more user friendly it will be perfect. 

I would eliminate the intermediate step of saving the file. A diaolg with both models  the model options, click apply and do all the steps that the user would have done by hand.

**Comment by rkhaotix** [comment]
Sure. I'll improve it in the next releases. Thanks for suggesting! :+1:
