### ISSUE TITLE
Automatic layout diagrams

### ISSUE THREAD

**Issue by fire** [pgmodeler/pgmodeler#588]
It would look visually better if we could layout the diagrams.

Here are also some examples of graph layout algorithms: https://github.com/noflo/noflo-ui/issues/53

Seems like the one noflo uses is Klay.

 http://rtsys.informatik.uni-kiel.de/~biblio/downloads/papers/jvlc13.pdf

Perhaps we can use this js library and run the code in qt's javascript engine. 

https://github.com/OpenKieler/klayjs

**Comment by rkhaotix** [comment]
It is on my plans to implement model layouts (auto arrangements). But I'll
need a bit time to study the better approach for pgModeler since this is a
quite complex problem and to get things worse we have some complex classes
on the project that will need refactoring before I start to work on this
feature.

btw, thanks for suggesting those algorithms.
Em 27/01/2015 05:25, "K. S. Ernest (iFire) Lee" <notifications@github.com>
escreveu:

**Comment by fire** [comment]
klayjs accepts json descriptions of the graphs and is explained in http://rtsys.informatik.uni-kiel.de/confluence/display/KIELER/KLayoutData+Meta+Model 

``json
var graph = {
  "id": "root",
  "properties": {
      "direction": "RIGHT", "spacing": 40
  },
  "children": [{"id": "n1", "width": 40, "height": 40}, 
               {"id": "n2", "width": 40, "height": 40}],
  "edges": [{"id": "e1", "source": "n1", "target": "n2"}]
};
```

KIELER/Klay is designed for organizing software diagrams. Not sure how hard it is to output the elements we need into json and modify the database visualization.

The original library is in Java so it's not possible to include it unless you want a Java devependency. However Javascript is part of Qt. It may be possible to use Qt's interfaces to perform computation in javascript and return it to c++.

**Comment by rkhaotix** [comment]
Don't get me wrong, but I prefer to understand the algorithms and implement a pure C++ solution integrated to pgModeler's code base. There are complex classes that may not fit the input needed by the klayjs you've mentioned or we need to do deep changes to generate the desired input. So, if we'll modify the code, why not implement a complete C++ solution?

**Comment by diordonez** [comment]
Related to #423

**Comment by AGPDev** [comment]
+1

**Comment by frinux** [comment]
+1

**Comment by aislanmaia** [comment]
I think one enhancement would be the links between tables get attached to anywhere, not only at the PK and FK localizations at the tables and the possibility to move them manually. At least manually we can organize the layout, because like it is right now is a mess on board.

**Comment by rkhaotix** [comment]
@aislanmaia You can disable that feature in the Settings > Relationships by checking the option second option in the dialog (see below)

![rel_conf](https://cloud.githubusercontent.com/assets/2205476/26725583/9ac97a58-4775-11e7-86ae-3608e9543f58.png)

This option causes the relationships to be connected to the table's center point instead of its left/right edges. The feature you're requesting is a bit more complicated but doable but it'll demand a certain time.

**Comment by aislanmaia** [comment]
Nice @rkhaotix , thanks for reply. One thing I noted is that the relationships generated for my model do not allow me modify the type of them. In the picture above we have 0:1, 0:n pattern, but in my case just appears n or 1 pattern on the both sides and I can't modify that. Anyway, nice job so far! :1st_place_medal:

**Comment by giulioprovasi** [comment]
hey guys, any news on this feat =
