### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by Mithrandir21** [pgmodeler/pgmodeler#620]
After many hours of trying to compile the source code I have managed to get a handle on what's what.
There are a lot of different issues and variables so I will sum up:
1. My environment was a complete clean Windows XP (no specific reason).
2. [Downloaded](http://www.postgresql.org/download/windows/) and installed PostgreSQL 9.3.6 (For Windows through standard installer)
   (NOTE: There were some issues with the "mingw32-make" not being able to use the "Program Files" path for PostgreSQL, so install it to "C:\PostgreSQL..." instead of "C:\Program Files".)
3. [Downloaded](http://download.qt.io/official_releases/qt/5.4/5.4.1/qt-opensource-windows-x86-mingw491_opengl-5.4.1.exe.mirrorlist) and installed Qt 5.4.1 with MinGW 4.9 32-bit and (Tools) MinGW 4.9.
4. [Downloaded](http://www.zlatkovic.com/libxml.en.html), unzipped, renamed entire folder (to "libxml") and then placed folder under "Qt\5.4\mingw491_32\include".
5. Added following entries to Environment Path:
   C:\Qt\5.4\mingw491_32\bin;
   C:\Qt\Tools\mingw491_32\bin;
   C:\Qt\Tools\QtCreator\bin;
   C:\PostgreSQL\9.3\bin;
6. Opened "pgmodeler.pri" and added the necessary paths:
   PGSQL_LIB = C:\PostgreSQL\9.3\lib\libpq.dll
   PGSQL_INC = C:\PostgreSQL\9.3\include
   XML_INC = C:\Qt\5.4\mingw491_32\include\libxml\include
   XML_LIB = C:\Qt\5.4\mingw491_32\include\libxml\bin\libxml2.dll
7. Opened the installed command line "Qt 5.4 for Desktop".
8. Navigated to the "pgmodeler-0.8" folder.
9. Ran "qmake pgmodeler.pro"
10. Ran "mingw32-make".
    Note: Weird issue with " #include < libpq-fe.h > " in resultset.h. Kept getting error in "mingw32-make" that it could not be found so I hardcoded the absolute path in resultset.h. ("C:\PostgreSQL\9.3\include\libpq-fe.h") Worked.
11. Ran "mingw32-make install".
12. Everything successful.
13. Opened the new folder "build" under "pgmodeler-0.8" and ran "pgmodeler".
14. Got error that "Application has failed to start because pgmodeler_ui.dll was not found."
15. Went into the "lib" folder in the same "build" folder and copied all the dll files in the root of "build".
16. Now the application opens, but I haven't tested everything.
    <br>

Note: HOLY MOLLY!! There was a lot of stuff going on with this compilation.
Any comments? Thoughts? Ideas? Suggestions?

I know you guys are now selling the binaries and I fully support that for those that cannot or don't want to compile, but I really think you guys should write some kind of guide for those that actually wish to compile. (At least before some someone else goes and does it. Or worse, starts making installers.)

**Comment by rkhaotix** [comment]
Congratulations to you @Mithrandir21! :+1: 

Well, about write a installation guide... There is a basic instruction [ quite outdated :( ] on Wiki pages:
http://www.pgmodeler.com.br/wiki/doku.php?id=installation

You can get more details about the variables by reading the comments on file pgmodeler.pri and pgmodeler.pro. They are reasonably documented in a way that those who intends to compile the software can understand the process and variables involved.

Additionally, in the user's guide there are detailed instructions on how compile pgModeler in all supported platforms. The user's guide (actually a kind of e-book) is sold to help the project's maintenance (as well the binary packages). Soon I'll rebuild the whole project's site and there will be a section (maybe a Wiki) where user's can get instructions on how compile/install as well on how use pgModeler (basic steps). Also, I always help everyone that wants to compile pgModeler for themselves (when I have free time to do that, of course). 

I think that with or without a compilation instruction I know that someone can generate binaries and distribute them free of charge. When a situation like that happens I'll have no reason to keep working hard on pgModeler. I really LOVE work on this project because I have so much positive feedback from users that this give me energy to continuously improve the software.

But we all know that just "love" don't pay bills. This is why I ask a fair price for the service of compilation and I'm really grateful to those that believes in the project's cause and potential giving some money to help (be in form of purchases or donations). Well, when the project stops to receive such collaborations I'll gradually abandon it because the time I spent on it in return of a few bucks I can do some freelancer works to gather money. :)

By the way, thanks for giving such detailed instructions. I hope you enjoy this project!

**Comment by lowjoel** [comment]
I just saw this. #655 should help with Windows compiles.

**Comment by 3str** [comment]
Hi, I followed the exact workflow as above on Windows 8.1. But when I run the compiled pgmodeler.exe, I get the following error.

Cannot find entry point _ZN10QArrayData10deallocateEPS_jj in utils.dll.

What's the cause? Thanks!

**Comment by lowjoel** [comment]
Sounds like using a wrong kind of Qt library. You'll need a DLL build of Qt.

**Comment by 3str** [comment]
Thanks for getting back to me so fast :-), but I'm not sure what to do next. I installed Qt 5.4 MinGW 4.9.1 (32-bit) OpenGL with qt online installer. Did I chose the wrong Qt installation or did I specify the wrong path in the configure file?

**Comment by rkhaotix** [comment]
Mix different dll versions may cause that too
Em 26/04/2015 22:49, "Joel Low" <notifications@github.com> escreveu:

**Comment by lourdas** [comment]
I read @Mithrandir21 's comments about compilation in Windows. They were very helpful. I finally managed to compile version 0.8.0 and after copying all files from the build\ directory to another system just to try out if something's missing (and it did, I had to copy many dll files to the other system), the application seems to start but it tries to find the conf\ directory from c:\pgmodeler-0.8.0 (the directory where I extracted the sources and compiled the application in the first system) and it fails to start. How do I solve this issue (tell pgmodeler not to look for conf\ in a hard coded path).

**Comment by felavm** [comment]
I did all the same. When I get to step 10, running "mingw32-make", I get the error:

2-g++"  -o obj\sqlexecutionwidget.o src\sqlexecutionwidget.cpp
src\sqlexecutionwidget.cpp: In static member function 'static void SQLExecutionW
idget::validateSQLHistoryLength(const QString&, const QString&, NumberedTextEdit
or*)':
src\sqlexecutionwidget.cpp:386:38: error: 'class QList<QString>' has no member n
amed 'join'
   cmds = buffer.mid(buffer.size()/2).join(QChar('\n'));
                                      ^
Makefile.Release:92884: recipe for target 'obj/sqlexecutionwidget.o' failed
mingw32-make[2]: *** [obj/sqlexecutionwidget.o] Error 1
mingw32-make[2]: Leaving directory 'C:/pgmodeler-develop/libpgmodeler_ui'
Makefile:34: recipe for target 'release' failed
mingw32-make[1]: *** [release] Error 2
mingw32-make[1]: Leaving directory 'C:/pgmodeler-develop/libpgmodeler_ui'
makefile:261: recipe for target 'sub-libpgmodeler_ui-make_first-ordered' failed
mingw32-make: *** [sub-libpgmodeler_ui-make_first-ordered] Error 2

Any idea how I can solve that?
Thanks for the installation guide!
