### ISSUE TITLE
Wrong path for plugins root dir on Windows.

### ISSUE THREAD

**Issue by tschoening** [pgmodeler/pgmodeler#623]
The following path is shown to me as the plugins root dir in Windows:

C:/Users/Raphael/Desktop/pgmodeler/build/plugins

Nothing happens if I click the folder icon or try to change this path by simply removing some characters or else. Seems to be read-only.

Not that I need/have plugin, I just recognized it by accident.

This is with version 0.8.0.

**Comment by rkhaotix** [comment]
Thanks the problem here is that the env var for plug-ins is not properly
configured by the installer. I'll fix that on next release.

p.S.: currently I'm on a vacation so maybe my answers may be delayed a bit
or i'll add additional comments when coming back home :)
Em 04/03/2015 14:04, "tschoening" <notifications@github.com> escreveu:

**Comment by rkhaotix** [comment]
Fixed in 0.8.1-alpha (in development)
