### ISSUE TITLE
Windows Compilling

### ISSUE THREAD

**Issue by inigosalvat** [pgmodeler/pgmodeler#660]
Hi,

First of all I want to give my congratulations for this great job.

After many hours working I was able to compile in windows 7 the source code using windeploy.sh.

The problem is that pgmodeler.exe looks for iconv.dll and intl.dll that aren't in the system.

Finally, I detect that those dll are libiconv.dll and libint.dll that are in the postgres distribution. Copying and renaming them after the installation I was able to run pgmodeler.

How can I fix that so the installer create a valid installation using the right dll's?

Thanks for your help,

Iñigo

**Comment by rkhaotix** [comment]
@inigosalvat  Thank you for compliments! I hope you enjoy the project.

About your question, you can change the variable ```DEP_LIBS``` around the line 49 and freely add the dll's names (and paths if needed) so they will be copied to folder where pgModeler resides. The variable is used to include additional dependencies (dlls) if they exists.

**Comment by inigosalvat** [comment]
But the question is, why is it looking for intl.dll in place of libintl.dll and iconv.dll in place of lobiconv.dll that are the dll's shipped with postgres?

**Comment by rkhaotix** [comment]
The deployment may differ from system to system and need to be tuned.

Well, I suspect that it must be a problem with xml2 dll. Try to copy the one shipped with PostgreSQL instead of the one in Qt bin dir (according to the windeploy.sh). AFAIK, Iconv  is a dependency of xml2 and intl is a dependency of iconv.

In conclusion: copy the libxml2.dll, iconv.dll and intl.dll from PostgreSQL installation. I think this will solve the problem.
