### ISSUE TITLE
The view editor needs to be more intuitive

### ISSUE THREAD

**Issue by RomanHargrave** [pgmodeler/pgmodeler#701]
A lot of my work with PGSQL does not usually involve an IDE. However, on the occasions that I have used PgModeler, I have liked it. However, there are some usability issues, and the first that comes to mind is the view editor dialog.

Firstly, it makes to no sense to allow an expression to be inserted in to the `SELECT ... FROM`, the `FROM ... WHERE` clause, and the `WHERE ... ;` clause _all_ at the same time, since in nearly all applications all of these clauses require different types of expression.

Secondly, pgmodeler does not generate fully qualified references to columns (e.g. `table.column`) when creating a view that takes data from multiple tables. This could get somwhat out of hand quickly if you have some large tables with potentially similar columns.

Thirdly, the generated source is not formatted at all, and could be much more readable.

I think that it might be a good idea to represent the view in the editor UI as a Tree, with the three aforemenetioned clauses as parent nodes, which may then have appropriate expressions added to them as children. It would also be nice if pgmodeler could display links to tables that were referenced in free form SQL code added to the view, though I imagine that that is more than likely due to the way DDL stores this information not making any assumptions about SQL code.

**Comment by GustaveCoste** [comment]
It would also be interesting to be able to reference another view without using an expression.

**Comment by rkhaotix** [comment]
@GustaveCoste,

This feature your are mentioning was discussed in a few issues in the past. The problem is, in order to be able to reference a view (and its columns, of course) without use an expression is a bit difficult because pgModeler can't determine the columns of that object. Technically speaking, there must be a mini SQL parser to read the view's definition and determine the columns' names. I'm planning to do this task but since it is a complex work I'll include it in a future release like 0.9.x or 1.0.x!

Best regards.
