### ISSUE TITLE
Set Postgis version in parameters

### ISSUE THREAD

**Issue by GustaveCoste** [pgmodeler/pgmodeler#704]
Hi Raphael, 
First of all, congratulations for the amazing tool you developed.
I would like to know if it is possible to set the postgis version of the database. I run postgis 2.1.7 but the database creation script shows :
CREATE EXTENSION postgis
      WITH SCHEMA public
      VERSION '2.0.3';

Thank you in advance.

**Comment by rkhaotix** [comment]
Hi Gustave,
Thank you so much for the compliment! It makes me quite happy to see people enjoying pgModeler! :)

About your problem... Yes, it's possible to use a different version of Postgis. I would like to remind you that only version 2.x is supported. Now, to change the version, open the extension  editing form and look for the field "version":

![extension](https://cloud.githubusercontent.com/assets/2205476/8498663/d21a8120-215f-11e5-95b5-bf365ef970d3.png)

... And the resulting code should be...
![extension1](https://cloud.githubusercontent.com/assets/2205476/8498670/de7c88d2-215f-11e5-9e00-0f53a1d65a94.png)


If after that you still can't change the version we have a bug which demands a bit investigation!
Best regards!

**Comment by GustaveCoste** [comment]
Nice ! I haven't seen this parameter, it know works fine!

Congratulations again for your software, it changed my work!

Best regards!

**Comment by dogosousa** [comment]
Hi Rafael,

I changed the postgis version to 2.2.2. However all of fucntions that were created with postgis 2.1.8 before were not changed. So when I run my code was crashing because I didn't have postgis 2.1.8 in my computer.. How can I clean this all functions of my model? Or how my model update all these functions?

![screenshot from 2016-08-22 16 55 08](https://cloud.githubusercontent.com/assets/7991205/17869432/96f45fe0-6889-11e6-9f2c-2fbca6f70d3b.png)

Thank you!

**Comment by rkhaotix** [comment]
Have you reverse engeenered the database prior the change in the postgis
version? If so, you have two choices. One: reverse engineer the db again or
two: open your model in a text editor and replace the 'postgis-2.1' by
'postgis-2.2'.

Em 22 de ago de 2016 17:00, "Diogo Caribé" <notifications@github.com>
escreveu:

Hi Rafael,

I changed the postgis version to 2.2.2. However all of fucntions that were
created with postgis 2.1.8 before were not changed. So when I run my code
was crashing because I didn't have postgis 2.1.8 in my computer.. How can I
clean this all functions of my model? Or how my model update all these
functions?

[image: screenshot from 2016-08-22 16 55 08]
<https://cloud.githubusercontent.com/assets/7991205/17869432/96f45fe0-6889-11e6-9f2c-2fbca6f70d3b.png>

Thank you!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/pgmodeler/pgmodeler/issues/704#issuecomment-241531372>,
or mute the thread

**Comment by yjacolin** [comment]
You have a sql script to upgrade your postgis version in your db. In Linux, look at /usr/share/postgresql/9.5/contrib/postgis-2.2/postgis_upgrade.sql

You can also run the SQL command: ALTER EXTENSION postgis UPDATE TO "2.2";
