### ISSUE TITLE
Creating a one-to-many relationship may not specify an OWNER value, which cannot be set through pgModeler

### ISSUE THREAD

**Issue by RomanHargrave** [pgmodeler/pgmodeler#705]
The many-to-many relationship editor has no option to configure ownership of a N-N relationship and its related tables, which can result in query-time access violation errors.

This becomes apparent when the following conditions are met:
- pgModeler was used to design an N-N relationship which abstracts the join table
- pgModeler is connected to the database server using an account other than that which will access the relationship
- pgModeler created the relationship on the server

Since pgModeler does not specify table ownership when using the N-N relationship editor, Postgres will by default set ownership of the N-N join table to whichever user created it. Should the N-N join table have been created with the intent that a different user have access to it, this presents an issue due to said user not having read or write access to that table. Upon further inspection, it is apparent that pgModeler avoids setting default ownership, and due to the join table being locked in the modeler (due to its being controlled by the N-N DDL relation), an owner cannot be set.

This should be solved by allowing an owner to be specified in the N-N relationship editor.

**Comment by rkhaotix** [comment]
Relationships objects are by far the most complex objects in this project, so as discussed here #579 (in pt_BR) the many-to-many relationship doesn't support the usage of custom schema/owner/tablespace for the generated table. In order to workaround this issue you need to convert the N:N relationship to a intermediate table by right-click on the relationship > Convert . This way you'll be able do handle all attributes of  the intermediate table.
