### ISSUE TITLE
Cannot create and assign a new sequence to a column when creating a new table

### ISSUE THREAD

**Issue by ehsanvakili** [pgmodeler/pgmodeler#706]
Version 0.8.0 Win32

Cannot create and assign a new sequence object to a field, when creating a new table. In this case the sequence object does not exist before creating the table.

To reproduce the issue follow these steps:
1) Add a new table to the model.
2) In the "Column" tab, click on the (+) button.
3) Choose a new name for your column, let's say "id".
4) Leave the Data Type as "samllint".
5) In the "Default Value" group box, choose the Sequence radio button and click on the magnifier icon.
6) Expand the Schema and public nodes respectively.
7) Right-click on the Sequence item and click on the "New Sequence" popup menu.

The sequence creation dialog doesn't show up.

**Comment by rkhaotix** [comment]
Actually, you've just found a bug on the object browser dialog. :)
... and gave me a good idea to improve the object creation. 

Instead of fix that bug I'll improve the dialog to permit the creation of objects in the way you have tried. Currently, you need to first create the sequence and then create the desired table/column.

**Comment by rkhaotix** [comment]
Made this in the commit c548c9eda0a01dc77811df81c75db9c376eec38a 
It's quite functional but still has some small issues with operation history, nothing that can affect the modeling process. I'll gradually correct them.
