### ISSUE TITLE
diff and views

### ISSUE THREAD

**Issue by rimbault** [pgmodeler/pgmodeler#711]
The diff function drop and recreate all my views each time.
Create code from diff : 

> -- object: public.v_param | type: VIEW --
> -- DROP VIEW IF EXISTS public.v_param CASCADE;
> CREATE VIEW public.v_param
> AS  SELECT tp.intitule AS parametre,
>     tp.id_type_parametre,
>     pa.id_application,
>     a.intitule AS application,
>     tp.valeur_default,
>     pa.valeur AS valeur_app
>    FROM ((type_parametre tp
>      LEFT JOIN parametre_application pa USING (id_type_parametre))
>      LEFT JOIN application a USING (id_application));;

View in Postgresql : 

> ```
>                          View "public.v_param"
>   Column       |          Type          | Modifiers | Storage  | Description 
> ```
> 
> -------------------+------------------------+-----------+----------+-------------
>  parametre         | character varying(40)  |           | extended | 
>  id_type_parametre | integer                |           | plain    | 
>  id_application    | integer                |           | plain    | 
>  application       | character varying(20)  |           | extended | 
>  valeur_default    | character varying(100) |           | extended | 
>  valeur_app        | character varying(100) |           | extended | 
> View definition:
>  SELECT tp.intitule AS parametre,
>     tp.id_type_parametre,
>     pa.id_application,
>     a.intitule AS application,
>     tp.valeur_default,
>     pa.valeur AS valeur_app
>    FROM type_parametre tp
>      LEFT JOIN parametre_application pa USING (id_type_parametre)
>      LEFT JOIN application a USING (id_application);

PGmodeler add brackets on the JOIN clauses.

**Comment by rkhaotix** [comment]
The diff process is quite experimental and often there'll be false positives.

In this case is not pgModeler that adds parenthesis to JOIN clauses. The problem is that pgModeler retrieves the view's definition using the function pg_viewdef() [1]. This function is the responsible for format and return the view's SQL code. So this is when the "problem" happens...

pgModeler gets a formatted code that differs from the original view's SQL (in the model) and then pgModeler thinks the view was changed when it wasn't. To minimize those false positives you can uncheck the "Force recreation of objects". Note that unchecking this option when you change constraints in the model, for instance, they will not be modified in the database because constraints can't  have important attributes modified by a simple ALTER command. That's why the force recreation option is checked by default.

[1] http://www.postgresql.org/docs/current/static/functions-info.html
