### ISSUE TITLE
pgModeler is unusable with dark Qt themes

### ISSUE THREAD

**Issue by nickguletskii** [pgmodeler/pgmodeler#718]
The colours are all messed up.

![KDE Breeze Dark](https://i.imgur.com/qW7Wfkj.png)

The current workaround is adding `export QT_STYLE_OVERRIDE=GTK+` to `pgmodeler.vars`, but ideally, pgModeler should use system colours.

**Comment by rkhaotix** [comment]
This is one limitation of pgModeler.  Since it uses its own stylesheets to
make UI as uniform as possible in the supported systems we have this side
effect . We have two options,  create a dark theme stylesheet or restore
the option to disable the usage of stylesheets.
Em 31/07/2015 13:39, "Nick Guletskii" <notifications@github.com> escreveu:

**Comment by nickguletskii** [comment]
Well, if you mix system colours with non-system colours, you are bound to have a non-uniform look even on supported systems. A solution would be to use custom colours everywhere, not just where pgModeler needs an additional colour.

**Comment by RomanHargrave** [comment]
It looks like PGModeler has bundled dark stylesheets or is using fewer application-specific styles. I am using PGModeler at 9271d9d452434151c278e1c1b324ce721ba2deea.
