### ISSUE TITLE
Suggestion: allow function bodies to be defined in external files

### ISSUE THREAD

**Issue by nickguletskii** [pgmodeler/pgmodeler#730]
This would make editing functions easier for those who use other editors to edit SQL and PL/pgSQL.

**Comment by rkhaotix** [comment]
Nice idea. :+1:

**Comment by Ox0000** [comment]
nickguletskii, can you elaborate on what you mean?
The way I understand this could be in two different ways:
- At the moment of definition, I can point to an external file and the contents gets included in the model file; from that point on, the external file is no longer needed
- When defining the object (in this case, function body), I point to the external file and every time that the object's source code is needed, the external file is consulted.

The former seems easily doable to me but for the latter, I think we'd need to look more into the actual scenario you're trying to accomplish.

**Comment by nickguletskii** [comment]
>When defining the object (in this case, function body), I point to the external file and every time that the object's source code is needed, the external file is consulted.

That's what I mean. The SQL editor in pgModeler is significantly worse than in many other editors, so I would like to use an external editor to write queries.

**Comment by rkhaotix** [comment]
The problem in referencing an external file is that if you move the model file to another computer, for instance, the source file of the function need to be moved together (this in my point of view can be annoying and error prone). I think the first option present by @Ox0000 is a bit more suitable.

Finally, I'm working on a built-in editor that I intend to release in 0.9.0. This editor will be integrated to any source code field present in pgModeler and can be triggered via keyboard short cut or another way (I'm still planning that)...

@nickguletskii you could detail what kind of features do you like to see in the source code editor? Currently we have a simple code completion, syntax highlighter and line numbers...

**Comment by rkhaotix** [comment]
The image below is a small sample of what I'm thinking. A simple form with options to load, save, search code, clear the input and use snippets. Once the code is in the shape user wants , he will click "Apply" and the code will be attached to the object.

![src_editor1](https://cloud.githubusercontent.com/assets/2205476/9554385/ca81e03a-4d9b-11e5-90d2-6b4be361842f.png)

**Comment by nickguletskii** [comment]
>The problem in referencing an external file is that if you move the model file to another computer, for instance, the source file of the function need to be moved together (this in my point of view can be annoying and error prone). I think the first option present by @Ox0000 is a bit more suitable.

This doesn't stop *any* other editors from splitting projects into multiple files. Just use relative paths!

>Finally, I'm working on a built-in editor that I intend to release in 0.9.0. This editor will be integrated to any source code field present in pgModeler and can be triggered via keyboard short cut or another way (I'm still planning that)...

This isn't enough to match the functionality of other SQL editors. It seems to me that you are working on pgModeler solo, and maintaining a powerful SQL and PL/pgSQL editor is a task that is hard to do even when you have a big team. Externalising queries is much easier than maintaining a whole editor.

>@nickguletskii you could detail what kind of features do you like to see in the source code editor? Currently we have a simple code completion, syntax highlighter and line numbers...

Auto code formatting, Ctrl + Click to see object definition, colour schemes, Tab/Shift + Tab to indent/deindent, etc...

**Comment by rkhaotix** [comment]
> This doesn't stop any other editors from splitting projects into multiple files. Just use relative paths!

I know that. I don't know if you read the source code but it'll be kinda difficult (not impossible) to do things that way. The question here is if it worth the effort! I'm not denying to implement it!

> This isn't enough to match the functionality of other SQL editors. It seems to me that you are working on pgModeler solo, and maintaining a powerful SQL and PL/pgSQL editor is a task that is hard to do even when you have a big team. Externalising queries is much easier than maintaining a whole editor.

Yes. I'm working alone in pgModeler. Occasionally I receive some pull requests. Also, I don't need to create a powerful editor right now! We can start with a small editor and improve it. This could be another good feature to make more users to adopt the tool. You seem a bit impatient! Remember, I'm aware of all missing or incomplete features and I'm working hard to improve or create them. :)

> Auto code formatting, Ctrl + Click to see object definition, colour schemes, Tab/Shift + Tab to indent/deindent, etc...

Well, some of these are a bit advanced but I'll plan how to do that!

**Comment by nickguletskii** [comment]
>I know that. I don't know if you read the source code but it'll be kinda difficult (not impossible) to do things that way. The question here is if it worth the effort! I'm not denying to implement it!

What I am saying is that it will be much easier to do than improve the editor.

>Yes. I'm working alone in pgModeler. Occasionally I receive some pull requests. Also, I don't need to create a powerful editor right now! We can start with a small editor and improve it. This could be another good feature to make more users to adopt the tool. You seem a bit impatient! Remember, I'm aware of all missing or incomplete features and I'm working hard to improve or create them. :)

What I am saying is that I think that you should be lazier. Don't duplicate the effort unless it's absolutely necessary.

**Comment by rkhaotix** [comment]
> What I am saying is that I think that you should be lazier. Don't duplicate the effort unless it's absolutely necessary. 

I absolutely agree! But we have to analyze that the feature you're suggesting (which looks good enough to me) maybe cannot satisfy a user who prefers to edit his code in the same application avoiding the use of external tools. Honestly, I think the two features are good, one a bit more difficult than the other to create...

**Comment by nickguletskii** [comment]
>But we have to analyze that the feature you're suggesting (which looks good enough to me) maybe cannot satisfy a user who prefers to edit his code in the same application avoiding the use of external tools. 

I agree! What I disagree with is that one feature replaces the other and that it's possible to match the more powerful editors feature-wise while working on a project solo. Maybe I just misinterpreted you.

**Comment by rkhaotix** [comment]
It's ok! My English is quite bad and I'm sure that I'm not expressing myself correctly!
Yes, it's really hard to match powerful editors and I'll not try to do that... not now, not alone! :)

I'm just trying to figure out the easiest path... Thinking a bit more, include external files is much easier. :)

**Comment by nickguletskii** [comment]
>It's ok! My English is quite bad and I'm sure that I'm not expressing myself correctly!

No, your English is fine! Thank you for the amazing work. I apologise if I sounded impatient earlier.

**Comment by rkhaotix** [comment]
No problem. Relax! :)
Thanks!

**Comment by rkhaotix** [comment]
I tried a basic implementation but honestly I don't like the added code complexity for the requested feature. I thought it was simple to do but there some details that is causing me some problems to keep working on the new feature. What I have done so far is the ability to load an external file and use its contents as the function's body according to the first item suggested by @Ox0000 on 28 Aug 2015. No problem here!

The real challenge comes for the second loading mode: the link or reference to an external file. According to what @nickguletskii and @Ox0000 said, it's a good idea to use relative paths for the linked file. So, thinking on that I added the option "Link file" in the function's source input. When selecting the file a tag ```{file:[relative_path]:[modification_date_in_msecs]}``` is generated (see the image).

![source_code](https://cloud.githubusercontent.com/assets/2205476/23035383/a8ea99e8-f45d-11e6-8b5c-662ed566d829.png)

For now,  ignore the tag details because they are used to optmize the code generation avoiding unnecessary loadings of the referenced file. What is bothering me right now is that I need to use the pgModeler's installation root as the base directory to generate the relative path to the SQL script which contains the function's body. It's not uncommon to have a team working in the same model in different machines with different systems and installation paths, so the whole model may break if the referenced file path does not matches the relative path registered in the tag even if it exists in the running machine. So, I added the ability to use a fallback path so in case of the file could not be found in its original path pgModeler will look for it in the .dbm file folder.

I suspended my work in this feature to try to figure out how to improve it and, more important, if it worth the effort to keep track of the file and reloading it whenever the function's SQL code is being generated. In my humble opinion it is better to manually load the source from external file than automatically load it everytime. I see two drawbacks here: 

1) if the referenced file is modified by accident or even deleted the SQL of the function will be malformed causing, in certain cases, the whole model's breaking;
2) inevitably, loading the function's body from a file is slower due to the disk reading than directly from memory. This fact may degradate other operations' performance, like export, validation and diff. Obviously, this is not applicable for machines equipped with solid state drives.

I suggest that we discard the idea of external file linkage and keep working only in the one-time loading of external files. So, based upon we have implemented right now, only the "Link file" in the image above and all its logic would be removed. So, @nickguletskii  you still can edit your function's bodies in your preferred editor and load the file in pgModeler.

Any suggestion? :)
