### ISSUE TITLE
import fails; possibly because name contains invalid characters

### ISSUE THREAD

**Issue by dlangille** [pgmodeler/pgmodeler#748]
I'm using v0.8.1 on OSX and importing from PostgreSQL 9.4.4

The screen shot below mentions object $1 and I vaguely recall using something like that years ago when setting up this database. I don't know how to track it down now.

![screen shot 2015-09-10 at 11 16 47 am](https://cloud.githubusercontent.com/assets/1626436/9792820/2e4ae2c4-57b0-11e5-82dd-c9f265e657f2.png)

Looking at the log (not attached; it was 119K), I see this at the top:

[4] src/baseobject.cpp (358)
  virtual void BaseObject::setName(const QString &)
    [ERR_ASG_INV_NAME_OBJECT] Assignment of a name which contains invalid characters!

[3] src/databasemodel.cpp (4811)
  Constraint *DatabaseModel::createConstraint(BaseObject *)
    [ERR_ASG_INV_NAME_OBJECT] Assignment of a name which contains invalid characters!
       ** <constraint name="$1" type="fk-constr" comparison-type="MATCH SIMPLE"
         upd-action="CASCADE" del-action="CASCADE" ref-table="public.report_frequency" table="public.report_subscriptions">
        <columns names="report_frequency_id" ref-type="src-columns"/>
        <columns names="id" ref-type="dst-columns"/>
</constraint>

Using pgAdmin, I find this for the table mentioned above:

![screen shot 2015-09-10 at 11 47 36 am](https://cloud.githubusercontent.com/assets/1626436/9793154/066bfbce-57b2-11e5-9b77-c39496086aff.png)

**Comment by rkhaotix** [comment]
The problem is exactly that: invalid characters in the object's name. The object naming in pgModeler follows almost all rules in this link: http://www.postgresql.org/docs/9.1/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

According to that document dolar signs aren't allowed in the start of string (unless you quote all the name, e.g., "$1"). In pgModeler user can't directly quote names in editing forms so if you use the dollar or other invalid character it'll raise errors.

Well, I must be wrong, but I assume that this is a database maintained for many years or generated by some kind of framework that used that name convention (a bit weird for me) even when the dollar signs were accepted because PostgreSQL can show them to you (via pgAdmin). 

The fact is, pgModeler can't support them right now. I can provide the fix but it'll available only in 0.8.2. As a workaround you can rename those constraints to get reverse engineering working...

**Comment by dlangille** [comment]
You mentioned 'unless you quote all the name', which made me look closer.  Here is the constraint as shown by pgAdmin:

    - Foreign Key: "$1"

    -- ALTER TABLE report_subscriptions DROP CONSTRAINT "$1";

    ALTER TABLE report_subscriptions
      ADD CONSTRAINT "$1" FOREIGN KEY (report_frequency_id)
          REFERENCES report_frequency (id) MATCH SIMPLE
          ON UPDATE CASCADE ON DELETE CASCADE;

**Comment by dlangille** [comment]
I will look at renaming them. Better names are... better.

**Comment by rkhaotix** [comment]
I agree! :)
Anyway, I'll add a small patch to the application in order to accept dollar signs in any portion of the name but this will cause the automatic quoting but I think this can solve this bug.

**Comment by rkhaotix** [comment]
Done!
If you are able to compile pgModeler you can test it for yourself! :D

Thanks for reporting this issue!

**Comment by dlangille** [comment]
Thank you.  I'm happy to test, but cannot devote the time to compile pgModeler myself.

Now.. if there were weekly/daily snapshots, I'd try them.  Otherwise, I'm waiting for the next release.

**Comment by rkhaotix** [comment]
Ok. I think I have enough set of fixes to release the 0.8.2-alpha. I'll try to release it in the next week. :)

**Comment by dlangille** [comment]
I'll be in for that.  My first goal: the database behind FreshPorts.org.  It was original created with a Sybase tool and has about 70 tables and 5 views.

**Comment by rkhaotix** [comment]
That's nice. A great opportunity to test pgModeler. :)
Thanks for all contribution! :+1:

**Comment by dlangille** [comment]
FYI, the import succeeded with v0.8.2.0-alpha.

It's difficult to view this screen shot, but:
![screen shot 2015-11-10 at 11 27 54 am](https://cloud.githubusercontent.com/assets/1626436/11068193/3ef945fc-879e-11e5-8870-381c2d232876.png)
