### ISSUE TITLE
Export SQL: Add option to "CREATE object IF NOT EXISTS"

### ISSUE THREAD

**Issue by selimt** [pgmodeler/pgmodeler#769]
The default behavior for schema export for object creation is to DROP the object before creating it (although by default the DROP statement is commented out). Can we have an option so that it creates the object only if it doesn't exist? This will allow a schema to have a non-destructive behavior if it is run over and over again. Ideally the option would be per object.

Thanks.
-Selim

**Comment by Rigare** [comment]
Hi Selim,
I know, this issue was written almost seven years ago, but just now I had the same problem and couldn't find a solution anywhere. After some trial and error, I found a way to solve the problem myself and would like to share the result for anyone who stumbles upon this problem. You can change the templates for the create statements in the schemas folder inside the pgModeler folder. Under sql you have to modify the *.sch file, for example the table.sch:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/19714539/190453664-5918dc0d-efca-473c-af40-716426d8891b.png">

After the modification the export will be created with this adjustments.

Best Regards,
Marco

**Comment by rkhaotix** [comment]
Out of curiosity , why do you need "IF NOT EXISTS" statement? The diff does not helps to incrementally create objects? I want to understand the problem just to see the real need to add this patch. Thanks.

**Comment by rkhaotix** [comment]
Hi @Rigare 

> We had the problem, that the exported SQL file from pgModeler creates a statement for creating a database, which is already present and should not be dropped, thus preventing the code from running. As well the tables should be dropped by running the SQL and this cannot be configured anywhere using the GUI, so we have customized this by ourselves.

Unless you need to run the script outside pgModeler (where the proposed solution is really needed), you can achieve the desired result by disabling the SQL code of the database object itself by right-clicking a blank area in the canvas and using the menu item Quick > Disable SQL.

![image](https://user-images.githubusercontent.com/2205476/190631012-57b09ab2-2a18-4f86-ae3f-3ebbbb48335b.png)

Alternatively, the database object code can be disabled in its editing form:

![image](https://user-images.githubusercontent.com/2205476/190631251-c6b81c07-e9e8-4a4f-8ce1-9861f9181b35.png)

The actions above disable only the ```CREATE DATABASE ...``` command, so you can run the export process in GUI by enabling the drop of the objects only in the following way:

![image](https://user-images.githubusercontent.com/2205476/190631510-c593ea49-22df-4fae-a8b8-e36312a1c30a.png)

In CLI, you must issue a command similar to:

```pgmodeler-cli --export-to-dbms --input demo.dbm --conn-alias local-db --drop-objects```
