### ISSUE TITLE
how to install or run the pgmodeler with the source  v0.8.1 I downloaded

### ISSUE THREAD

**Issue by libozhang** [pgmodeler/pgmodeler#773]
there is no pgmodeler file under the unzip directory pgmodeler-0.8.1 when I tried to run ./start-pgmodeler.sh

./start-pgmodeler.sh: line 17: /home/pgmodeler-0.8.2-alpha/pgmodeler: No such file or directory

**Comment by disperun** [comment]
If you have downloaded the zip package from github you need to compile the source first. Check the docs http://pgmodeler.com.br/wiki/doku.php?id=installation. You can also find some hints how to compile and install pgmodeler within issue tickets (e.g. windows https://github.com/pgmodeler/pgmodeler/issues/620). 

Otherwise you can get the precompiled binary package (installer) from http://pgmodeler.com.br/recover.php by donating a small amount of money to the author ( http://pgmodeler.com.br/purchase.php ).
