### ISSUE TITLE
installation on OpenSuse 42

### ISSUE THREAD

**Issue by dewid1985** [pgmodeler/pgmodeler#776]
Everything is done for documentation/WIKI

qmake pgmodeler.pro
/opt/pgmodeler-develop/pgmodeler.pri:21: defined(function, type): unexpected type [var].
/opt/pgmodeler-develop/pgmodeler.pri:24: defined(function, type): unexpected type [var].

**Comment by Snolag** [comment]
I had pretty much the same problem today, when compiling pgmodeler-0.8.2-beta on OpenSuse Leap 42.1.

The problem was, that my qmake uses qt4 not qt5 which is needed by pgmodeler.
You can check this by typing:
`qmake -v`
which resulted in: `QMake version 2.01a Using Qt version 4.8.6 in /usr/lib64
`
The qmake-version which uses qt5 on my system can be found at:
`
/usr/lib64/qt5/bin/qmake
`
So executing:
`/usr/lib64/qt5/bin/qmake pgmodeler.pro`
instead of `qmake pgmodeler.pro` solved this for me.

**Comment by dewid1985** [comment]
Thank you!!!
