### ISSUE TITLE
Making use of mouse's middle click to pan the diagram

### ISSUE THREAD

**Issue by ziadloo** [pgmodeler/pgmodeler#782]
Perhaps this is more of an opinion but as someone who has worked with so many software incorporating a graphical user interface, I find it most comfortable if the **middle click** is used for **panning** the diagram.

Right now one should find an empty space on the canvas to be able to pan the diagram, but using middle click one can easily pan it even if there's no empty space available in the current view.

**Comment by rkhaotix** [comment]
Hi!
Sorry the delay on response. 

Thanks for your suggestions. Currently, the default implementation of the framework is to use left button click and drag to pan the view. I need to do a custom implementation to make the pan using the middle button work. Since I suspended the addition of new features in 0.8.x in order to dedicate only to bug fixes I'll mark this issue as an enhancement for release 0.9.0 :)
