### ISSUE TITLE
create geometry column failed (addgeometrycolumn missing)

### ISSUE THREAD

**Issue by geohiggins** [pgmodeler/pgmodeler#861]
I would like to create a geometry column. The postgis-extension is activated.
When I check the SQL-File, I can't find the SQL-statement "Select addgeometrycolumn..." is there a trick solve this issue in pgmodeler?

![bildschirmfoto 2016-09-05 um 11 44 36](https://cloud.githubusercontent.com/assets/22002329/18244153/d2faef1a-735e-11e6-82d9-37bed1af6da2.png)
![bildschirmfoto 2016-09-05 um 11 44 16](https://cloud.githubusercontent.com/assets/22002329/18244159/d6f5204a-735e-11e6-9ab1-e32cf0aeb838.png)

Postgres 9.3, postgis 2.1.4, pgmodeler 0.8.2 on Mac 10.11

**Comment by rkhaotix** [comment]
It sounds that the extension is being created after the table. Try to
validate the model.

Em 5 de set de 2016 06:59, "geohiggins" <notifications@github.com> escreveu:

I would like to create a geometry column. The postgis-extension is
activated.
When I check the SQL-File, I can't find the SQL-statement "Select
addgeometrycolumn..." is there a trick solve this issue in pgmodeler?

[image: bildschirmfoto 2016-09-05 um 11 44 36]
<https://cloud.githubusercontent.com/assets/22002329/18244153/d2faef1a-735e-11e6-82d9-37bed1af6da2.png>
[image: bildschirmfoto 2016-09-05 um 11 44 16]
<https://cloud.githubusercontent.com/assets/22002329/18244159/d6f5204a-735e-11e6-9ab1-e32cf0aeb838.png>

Postgres 9.3, postgis 2.1.4, pgmodeler 0.8.2 on Mac 10.11

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pgmodeler/pgmodeler/issues/861>, or mute the thread

**Comment by geohiggins** [comment]
Thankx you guided me to the solution. I forgot to select the correct DB :-)

Solved!

**Comment by white-shadow90** [comment]
Hello,

I didn't know that we had to create the extension before creating tables. I thought the order was défined by the app... so how can I rearrange the source code so that the creation of extension come first and so that I can validate my model getting this error ?

Congrates for the job you've realized to make this app.
