### ISSUE TITLE
Diagram Enhancements: 1) Hide column data types 2) Print to PDF

### ISSUE THREAD

**Issue by blancsys** [pgmodeler/pgmodeler#863]
Hello,

First of all, congratulations for your software! I tested a dozen of open source tools to create ERD diagrams and PgModeler is the best tool by far!

I think that the PgModeler's diagram system just needs 2 more features to achieve the perfection :)

1) Add the ability to hide the column types. I mean, add the ability of just show the column names (nothing more) in the diagram. On big diagrams with a lot of tables, include the column data type makes the table area bigger and the diagram looks bloated. In my case, most of times I just need see the table name and the name of each table column (it's easy guess the column type just seeing the column name)

2) I see that it's possible export the diagram to an image (like a .png file). However, also have the ability to export to PDF could be great, because makes far simpler print big diagrams on several pages (when the diagram doesn't fit the printer paper size, for example A4)

Thank you very much in advance!

Best Regards

**Comment by rkhaotix** [comment]
Hi Alex!

Thank you so much for your feedback!  I'm glad to see that you really
enjoyed pgmodeler!

Your suggestions are great. Currently, I am unable to work in the project
due to a surgery in the shoulder I made a few days ago.

As soon as I'm back I will think on a way to include these features you are
talking!

Best regards

Em 23 de set de 2016 15:35, "Alex Blanc" <notifications@github.com>
escreveu:

**Comment by blancsys** [comment]
Hi Raphael!

Thank you very much for your quick reply.

Sure, take your time. I wish you a speedy recovery from your surgery.

Thank you very much in advance!

Best Regards
