### ISSUE TITLE
PostgreSQL 9.6 support

### ISSUE THREAD

**Issue by archenroot** [pgmodeler/pgmodeler#866]
Hi, I purchased this wonderful piece of software, but database version 9.6 which I use is not supported yet, can I somehow easily override this limitation and try to use it with 9.6? I have very basic schema and features used in this case -> my work is just POC experiment.

If I cannot override manually, is there some road-map when 9.6 will be supported.

This is really nice piece of software. 

Thank you.

**Comment by rkhaotix** [comment]
Hi @archenroot 

Thank you so much for your support! It makes me really happy to see that you enjoy pgModeler!

Currently there is no support to PostgreSQL 9.6 and it can't be overriden easily. It demands a change in the core to include that version. 

I usually update the version support in my project as soon as a new release of the dbms is out... just to give the user the chance to at least connect to the system. The new features related to the new database version are introduced gradually...

Unfortunately, in the middle of this year this cycle was broken because I had to do a surgery in my shoulder ( a litlle gift for too many work :p ) and I'm in the middle of recovering process.. But I'm prohibited to touch a computer to code until December. So, unfortunately, I have to say that the full support to 9.6 will come only in the beggining of the next year! :(

I'll try to provide a small preview of 0.9.0 (under development) and include the support to 9.6 in the next weeks.

Anyways, thank you so much!

**Comment by archenroot** [comment]
I understand, thanks for your work!

**Comment by archenroot** [comment]
I red completely your message now :-) I wish you get better soon, health is at first place (when you don't play some interesting game in time of course :-))

To my case, I am using only tables(no other object types), with PK, FK, fields are type of integer or text, end of story. You think current modeller need to be reworked a lot to get it working?

**Comment by rkhaotix** [comment]
Thanks for understanding! Yep... I'm playing a lot of games during this recovering process. Now, I'm Waiting my Fallout 4 (ps4) copy to arrive and start to play this masterpiece :)

About your question, the current stable release can deal quite well with tables, pks and fks. Simple models are not a problem for pgmodeler.  But if you face some problem do not hesitate in ask for help! ;)

**Comment by archenroot** [comment]
Ok, but how I remove the message about compatibility? When I try to establish connection to database from modeler, it screams about current version 9.6, but valid are: 9.5, 9.4, etc...

Can I override this version, I also notice there is new alpha version 0.9 available, can be this solution to my issue?

I of course understand possible instability, etc.

**Comment by archenroot** [comment]
Ok, I downloaded Alpha 0.9 and it works now :-), thanks a lot for help, I am going to play a little with this nice toy :-)
