### ISSUE TITLE
relation already exists during diff apply

### ISSUE THREAD

**Issue by Tahaan** [pgmodeler/pgmodeler#890]
Various operations fails with an error like this:

The object childdoc_inherits_assetdoc (Relationship) already exists on gv2 (Database)!

In particular this occurs when importing all schemas or when applying a diff to a database.

To reproduce:
1. Create a schema
2. Create a table and an inherited table on this table.
3. Clone the schema.
pgdump -s --schemaname="sourceschema" | sed 's/soureschema/targetschema/' | psql 
4. Import from database (select only one of the schemas to import) into pgmodeler.
5. Make some changes, eg Add a table
6. Apply diff back to database

Alternative way to reproduce the problem:  In the above sequence, at step nr 4 select two or more schemas with the same inherited tables.

The problem occurs only if there are inherited tables with the same name in multiple schemas.

The problem can be reproduced at will.

The problem occurs with pgmodeler 0.9.0 on Linux and against PG 9.5

Workaround: export to an SQL file and then apply manually.

To test that this is indeed caused by the inherited tables, drop the inherited tables in the OTHER schema and run the diff again - it succeeds.

This is a major problem in my environment as I have hundreds of copies of the schema, all with the exact same table names, etc.  This is used for tenant partitioning.

**Comment by rkhaotix** [comment]
Thanks Johan for such detailed report.

I know exactly where to fix to avoid this error. The automatic relationship
naming is not considering the situation where tables with the same name can
reside different schemas.

The fix will be available in the next release: 0.9.0-alpha1


Em 11 de jan de 2017 12:03, "Johan Hartzenberg" <notifications@github.com>
escreveu:

Various operations fails with an error like this:

The object childdoc_inherits_assetdoc (Relationship) already exists on gv2
(Database)!

In particular this occurs when importing all schemas or when applying a
diff to a database.

To reproduce:

   1. Create a schema
   2. Create a table and an inherited table on this table.
   3. Clone the schema.
   pgdump -s --schemaname="sourceschema" | sed
   's/soureschema/targetschema/' | psql
   4. Import from database (select only one of the schemas to import) into
   pgmodeler.
   5. Make some changes, eg Add a table
   6. Apply diff back to database

Alternative way to reproduce the problem: In the above sequence, at step nr
4 select two or more schemas with the same inherited tables.

The problem occurs only if there are inherited tables with the same name in
multiple schemas.

The problem can be reproduced at will.

The problem occurs with pgmodeler 0.9.0 on Linux and against PG 9.5

Workaround: export to an SQL file and then apply manually.

To test that this is indeed caused by the inherited tables, drop the
inherited tables in the OTHER schema and run the diff again - it succeeds.

This is a major problem in my environment as I have hundreds of copies of
the schema, all with the exact same table names, etc. This is used for
tenant partitioning.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pgmodeler/pgmodeler/issues/890>, or mute the thread
