### ISSUE TITLE
DYLD, [0x1] Library missing (mac)

### ISSUE THREAD

**Issue by cdekok** [pgmodeler/pgmodeler#896]
I have followed the steps to compile pgmodeler only when I run it i get the following error,
am i missing a dependency?

```
Process:               pgmodeler [89553]
Path:                  /Applications/pgmodeler.app/Contents/MacOS/pgmodeler
Identifier:            br.com.pgmodeler.pgModeler
Version:               0.8.0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           pgmodeler [89553]
User ID:               502

Date/Time:             2017-01-17 09:19:19.131 +0100
OS Version:            Mac OS X 10.12.2 (16C67)
Report Version:        12
Anonymous UUID:        533928DC-81EE-8ADD-B56C-3066B471B156


Time Awake Since Boot: 340000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing
```

**Comment by israelins85** [comment]
execute:

install_name_tool -change libpgmodeler_ui.1.dylib @rpath/libpgmodeler_ui.1.dylib /Applications/pgmodeler.app/Contents/MacOS/[BIN_NAME]
install_name_tool -change libobjrenderer.1.dylib @rpath/libobjrenderer.1.dylib /Applications/pgmodeler.app/Contents/MacOS/[BIN_NAME]
install_name_tool -change libpgconnector.1.dylib @rpath/libpgconnector.1.dylib /Applications/pgmodeler.app/Contents/MacOS/[BIN_NAME]
install_name_tool -change libpgmodeler.1.dylib @rpath/libpgmodeler.1.dylib /Applications/pgmodeler.app/Contents/MacOS/[BIN_NAME]
install_name_tool -change libparsers.1.dylib @rpath/libparsers.1.dylib /Applications/pgmodeler.app/Contents/MacOS/[BIN_NAME]
install_name_tool -change libutils.1.dylib @rpath/libutils.1.dylib /Applications/pgmodeler.app/Contents/MacOS/[BIN_NAME]


replace [BIN_NAME] for each one above:
	pgmodeler
	libpgmodeler_ui.1.dylib
	libobjrenderer.1.dylib
	libpgconnector.1.dylib
	libpgmodeler.1.dylib
	libparsers.1.dylib
	libutils.1.dylib

**Comment by israelins85** [comment]
This is the same described on: https://github.com/pgmodeler/pgmodeler/issues/779

**Comment by cdekok** [comment]
thanks i kinda gave up on it but today tried again and it was working now 👍

**Comment by sagarbest1** [comment]
Process:               webhook-electron [5638]
Path:                  /Volumes/VOLUME/*/webhook-electron.app/Contents/MacOS/webhook-electron
Identifier:            com.electron.webhook-electron
Version:               1.0.0 (1.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           webhook-electron [5638]
User ID:               501

Date/Time:             2020-03-17 12:04:27.614 +0530
OS Version:            Mac OS X 10.15.3 (19D76)
Report Version:        12
Anonymous UUID:        E8D57AC3-5578-30EC-649C-CB398CA00349

Sleep/Wake UUID:       185536B7-2C54-4957-9D65-86D53955D359

Time Awake Since Boot: 90000 seconds
Time Since Wake:       870 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Volumes/VOLUME/*/webhook-electron.app/Contents/MacOS/webhook-electron
  Reason: image not found

Binary Images:
       0x10712a000 -        0x10712aff3 +com.electron.webhook-electron (1.0.0 - 1.0.0) <ABFD2757-7204-36C7-801D-5DE755CB8C60> /var/folders/*/webhook-electron.app/Contents/MacOS/webhook-electron
       0x10dfbc000 -        0x10e04ccb7  dyld (733.8) <EBC07CB6-870A-3A8E-B48A-67F62EA161F3> /usr/lib/dyld

Model: MacBookPro9,2, BootROM 230.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2.5 GHz, 6 GB, SMC 2.2f44
Graphics: kHW_IntelHD4000Item, Intel HD Graphics 4000, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x0198, 0x393930343334322D3031382E413030472020
