### ISSUE TITLE
Object dialogs lose all data after switching workspaces

### ISSUE THREAD

**Issue by therealgaxbo** [pgmodeler/pgmodeler#934]
Switching to a new workspace with an object add/edit dialog open causes all data in the dialog to be lost after switching back.

Steps:
* Open 'New Table' dialog
* Set name, add fields etc
* Switch to new workspace
* Switch back to first workspace

Expected:
Dialog contains all data that had been entered

Actual:
All table columns are removed, all text fields are blank

Tested on pgmodeler-0.8.2 and 0.9.0-beta
Window manager/OS: Mate / Fedora 25

**Comment by rkhaotix** [comment]
Well, that's really not expected. But I blame the window manager that is not honoring the dialog modality. Once opened a dialog the user can't switch between workspaces. He should close the dialog first.

This problem doesn't occurs in Windows, macOS or Linuxes running KDE (the default WM to run pgModeler).

**Comment by therealgaxbo** [comment]
Hmm...I'd be very surprised is a modal dialog in an app prevented me being able to view a different workspace.

I've since tested it in Gnome and KDE - Gnome shows the same bug, but I can confirm it works fine in KDE.  KDE _does_ allow me to move between workspaces, but when I return the dialog still contains data.

**Comment by rkhaotix** [comment]
The problem lies in the current way pgmodeler is implemented. We handle
live objects in the memory. So the modal dialogs are used to prevent
crashes due to objects removal while creating an object in a dialog. A
simple example would be: you're editing a table in the dialog, supposing
that you really can switch between workspaces or handle other objects
simultaneously, you accidentally delete a schema referenced by the table
you're manipulating... In the moment you confirm the changes in the table
closing the dialog the software will crash because it will try to reference
an object that was destroyed previously.

In future releases I will change that behavior. But for now, there is no
official support to switch between loaded models.

Em 5 de abr de 2017 12:18, "therealgaxbo" <notifications@github.com>
escreveu:

Hmm...I'd be very surprised is a modal dialog in an app prevented me being
able to view a different workspace.

I've since tested it in Gnome and KDE - Gnome shows the same bug, but I can
confirm it works fine in KDE. KDE *does* allow me to move between
workspaces, but when I return the dialog still contains data.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pgmodeler/pgmodeler/issues/934#issuecomment-291895423>,
or mute the thread

**Comment by therealgaxbo** [comment]
Ah, I think you misunderstand me - I don't mean switching between different models within pgmodeler (I agree it would be normal for a modal dialog to prevent that).  I mean switching to a different workspace within the window manager (aka virtual desktop).

Hope that's clearer.

**Comment by rkhaotix** [comment]
Ohhhh... I understand now! 😄
My bad!

Well, in that case I still blame the WM because it is obligated to keep
data when doing the switching :)

Em 5 de abr de 2017 12:42, "therealgaxbo" <notifications@github.com>
escreveu:
