### ISSUE TITLE
Failed to check updates

### ISSUE THREAD

**Issue by mrmuskrat** [pgmodeler/pgmodeler#949]
When I start pgmodeler it attempts to check for updates. It then create a window titled "Failed to check updates" with the text "The update notifier failed to check for new versions! Please, verify your internet connectivity and try again! Connection error returned: Error transferring https://www.pgmodeler.com.br/checkupdate?version=0.8.2 - server repled: Forbidden."

When I try that URL in Chrome it works and I receive back JSON showing "new-version":"0.9.0-beta","date":"April 04, 2017", etc...

**Comment by zrod** [comment]
Same issue here, I'm on debian stretch.

**Comment by christiaanwesterbeek** [comment]
Me too. I'm on Mac High Sierra

**Comment by christiaanwesterbeek** [comment]
Are you using a deprecated ssl protocol? If you're using some openssl lib that uses SSLv3, I'm sure that's disabled on Mac due to POODLE. That would explain the error I'm seeing...

**Comment by rkhaotix** [comment]
The problem is that the new site address is https://pgmodeler.io and the certificate is associated to that address. The old address https://pgmodeler.com.br is not secured via SSL anymore, instead it only redirects to the .io 

What's is happening is that pgModeler is trying to check updates on the old address and is getting security issues related to the certificate. This can be fixed only by updating the address in the code since I can't do much about the site server's configuration (I don't have access to it).

**Comment by sanx2017** [comment]
I am getting the same issue. On Windows 10 though.

**Comment by kellington** [comment]
still an issue

**Comment by christiaanwesterbeek** [comment]
@kellington What is implied here that it won't ever be fixed unless you [download](https://pgmodeler.io/download) the latest version manually. I've done that too. That latest version 0.9.1-beta1 (take note of the last 1 in that version) will check the new site for updates which is secured.

**Comment by rkhaotix** [comment]
Exactly. There's no other way to fix this issue, the user need to download the new version of the tool manually.
