### ISSUE TITLE
Table trigger and append SQL 

### ISSUE THREAD

**Issue by dldamilola** [pgmodeler/pgmodeler#961]
I have a table with trigger before insert fore each row and append SQL with insert queries.
In export and validate I see all insert queries before creating trigger. 
Is it possible to append SQL after all table triggers and other stuff?

**Comment by rkhaotix** [comment]
Use the "Prepend SQL" tab instead of "Append SQL" in Custom SQL dialog.

**Comment by dldamilola** [comment]
What? Prepend = before create table. Append = after create table. 
If is like this:

- table
  - prepend
  - create
  - append
- trigger
  - prepend
  - create
  - append
- foreign key

So I have to move insert queries to append SQL for trigger. Quite strange.

**Comment by rkhaotix** [comment]
Oops... sorry. My bad!
I misinterpreted you.

You're right. Is there a possibility to you to send me a copy of your model?

**Comment by rkhaotix** [comment]
I think I know what is!

Since in pgModeler everything is an object the trigger is being created separated from its parent table and right after the execution of the inserts that are appended to the table's SQL. The solution for your case is to move the inserts from table to the trigger bacause the order of execution is important here.

I'm planning to create a more flexible way to add custom SQL command by introducing some kind of generic SQL objects which can have the creation order defined by the user. I hope I can add it still in the 0.9.0 develpment.

**Comment by dldamilola** [comment]
Yeah. It is not only with triggers. With FK also the same. And rules. They all goes after append SQL for create table.
It will be great to manipulate this order!
