### ISSUE TITLE
Easily add/move relationship lines

### ISSUE THREAD

**Issue by pmcvay** [pgmodeler/pgmodeler#977]
This may already be implemented but I am not sure how to accomplish this. For the explanation I will assume only two tables (table1 and table2). Table2 has a foreign key connecting it to Table1. I would like to make the relationship line between the two tables follow a path like a top hat outline (\_|-|_). This requires creating 4 break points and creating right angles. 

The limitations currently with my knowledge is that you can only create two break points by selecting the 'two right angles' options and then you can drag the break points but only to a grid line. This means if you drag a break point it will not be horizontal with the column name because the column name isn't centered on a grid line. 

Essentially, what I would like implemented is the ability to click on the line and add a break point where it is clicked and then the break point to be able to snap to the column name height in addition to the grid lines. As a side note, I would also like to hide the diamond and the relationship name.

Finally, I saw issue #393 was closed. Has this been implemented in the latest release?

I think this is a great program and I happily donated to the project yesterday. Thanks

**Comment by rkhaotix** [comment]
Hi!

Currently we don't have the mentioned way to break lines (top hat) but I found it great, I'll schedule it for future releases. I can't do much right now because I'm on a vacation and a PC is the last thing I want to see! :P
I'll work on it in August.

About adding points to the lines, just hold Shift and click anywhere in the relationship line then a break point will be added. Of course, the point can be moved freely.

The issue #393 was implemented long ago , if my memory serves, during the implementation of 0.8.0. Basically, pgModeler compares a loaded model with the database that represents the first and generates the SQL commands so the DB can be synchronized with the model.

Thanks for your feedback and donation! :)

**Comment by pmcvay** [comment]
Fantastic! Have a great time on vacation! I completely understand not wanting to look at a PC. 

The shift-click was exactly what I was looking for. The only issue I hope will be simple to implement in future releases is the ability to drag the break point to align with the break points at the ends where it connects to the column name. As of now, I can only drag it to grid points. The OCD part of me doesn't like have a slightly different then 90 degree angle before it connects to the table. Or a workaround would be having each column name in the table spaced the same as the as the grid lines. 
![image](https://user-images.githubusercontent.com/16722345/27971236-8369dd22-6317-11e7-8102-0ee9aa1a3fad.png)

Thanks for the quick response!
