### ISSUE TITLE
Horrible application scale on Debian 9

### ISSUE THREAD

**Issue by cloud-rocket** [pgmodeler/pgmodeler#989]
I moved from Ubuntu 16.04 to Debian and installed pgModeler. For some reason I am experiencing impossible to work with elements scale (I am working with dual monitors - laptop 14" and desktop 23", both working with 1920x1080 ):
I am having huge icons and spacing with small fonts:

Example on 14" laptop
![image](https://user-images.githubusercontent.com/2440892/29750278-7f447760-8b45-11e7-925f-7e7cd5db0e80.png)

Horizontal scrollbar is missing on 14" as well (only the bottom toolbar with huge buttons is seen)

Example on 23" desktop:
![image](https://user-images.githubusercontent.com/2440892/29750289-ade6f7f0-8b45-11e7-8ae1-5b65c2903885.png)

The configuration window extends beyond the monitor without ability to reduce it (only to expand it more).

![image](https://user-images.githubusercontent.com/2440892/29750317-4572e87c-8b46-11e7-9eb3-23d196555bd0.png)

Thanks

**Comment by rkhaotix** [comment]
Well, the automatic  scale feature is not perfect. There's lots of
combinations of monitors and resolutions so pgModeler try to "guess" the
better adjustment so this is error prone like your case.

The only thing I think is not right in your report is that both monitors
have the same resolution. If this is true the scale feature wouldn't be
activated.

Anyways I'll try to improve it.

Em 27 de ago de 2017 10:36 AM, "Meir Tseitlin" <notifications@github.com>
escreveu:

I moved from Ubuntu 16.04 to Debian and installed pgModeler. For some
reason I am experiencing impossible to work with elements scale (I am
working with dual monitors - laptop 14" and desktop 23", both working with
1920x1080 ):
I am having huge icons and spacing with small fonts:

Example on 14" laptop
[image: image]
<https://user-images.githubusercontent.com/2440892/29750278-7f447760-8b45-11e7-925f-7e7cd5db0e80.png>

Example on 23" desktop:
[image: image]
<https://user-images.githubusercontent.com/2440892/29750289-ade6f7f0-8b45-11e7-8ae1-5b65c2903885.png>

The configuration window extends beyond the monitor without ability to
reduce it (only to expand it more).

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pgmodeler/pgmodeler/issues/989>, or mute the thread

**Comment by cloud-rocket** [comment]
Both monitors have the same resolution, but different physical sizes.

But the strange thing is that before I moved to Debian 9, I was using pgModeler on Ubuntu 16.04 on the very same computer with same monitor attached and it worked perfectly well. I was also using Cinnamon/Unity interfaces - and both of them were not scaling the application displaying them nicely. 

This is why I suspect there is some weird configuration I am not aware of....

**Comment by cloud-rocket** [comment]
Is there anyway to disable the scaling totally?

**Comment by cloud-rocket** [comment]
I found a workaround - but I assume this is some kind of bug in pgModeler:
When I run ```xrandr --output eDP-1  --scale .9x.9 --mode 1920x1080``` on one of the screens (eDP-1 in this case), pgModeler loads correctly on both screens. But when I switch back to scale 1x1 - it loads badly again (when switching back to 1x1 without reloading pgModeler - it stays ok).

Hope it helps somehow

**Comment by rkhaotix** [comment]
The physical size would not have to interfere! :/

On my development machine I have a 23" monitor running 1080p and another
24" running 2K and pgModeler runs fine scaling the windows/fonts properly
on the bigger screen.

I'll try to add a switcher for the automatic scaling in general settings.

Em 28 de ago de 2017 11:50 AM, "Meir Tseitlin" <notifications@github.com>
escreveu:

I found a workaround - but I assume this is some kind of bug in pgModeler:
When I run xrandr --output eDP-1 --scale .9x.9 --mode 1920x1080 on one of
the screens (eDP-1 in this case), pgModeler loads correctly on both
screens. But when I switch back to scale 1x1 - it loads badly again (when
switching back to 1x1 without reloading pgModeler - it stays ok).

Hope it helps somehow

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pgmodeler/pgmodeler/issues/989#issuecomment-325375564>,
or mute the thread

**Comment by truewar** [comment]
I have the same issue on Laptop on ArchLinux. Now I have only one Monitor (laptop one) and still bad size.

`
# xrandr 
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 8192 x 8192
eDP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 309mm x 175mm
   1920x1080     60.01*+
   1400x1050     59.98  
   1280x1024     60.02  
   1280x960      60.00  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   800x600       60.00    60.32    56.25  
   700x525       59.98  
   640x512       60.02  
   640x480       60.00    59.94  
   512x384       60.00  
   400x300       60.32    56.34  
   320x240       60.05  
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
`

If I launch **pgmodler** then run
`xrandr --output eDP-1 --scale .9x.9 --mode 1920x1080`
and then 
`xrandr --output eDP-1 --scale 1x1 --mode 1920x1080`
pgmodeler stays OK until restart

**Comment by cloud-rocket** [comment]
@rkhaotix, can you pls provide what desktop settings are you using to define font/icons scaling? This way we can fix those settings in Cinnamon/etc......

Thanks

**Comment by archenroot** [comment]
@rkhaotix Just another point from my perspective when comparing 0.9.* (beta) against previous major versions I see big improvement on my 4K screens running on Gentoo system. Some buttons for example on "new table" are smaller then I would like to see, but in general, good job done here...

**Comment by rkhaotix** [comment]
@archenroot if possible share with us some screenshots so I can have an idea on how good/bad it is on 4K screen  and see if I need to do more adjustments in the resize procedure.  Anyways, thanks to share your opinions/thoughts. :)

**Comment by archenroot** [comment]
@rkhaotix sure
![image](https://user-images.githubusercontent.com/553512/29938709-ecd44cdc-8e89-11e7-82e5-cf395cd23143.png)
![image](https://user-images.githubusercontent.com/553512/29938771-2759f9f6-8e8a-11e7-9b10-051e74cc366b.png)

Also note, I am on Gentoo Linux with KDE desktop where actually my Plasma is running on 5.6.2-r1 version as this could also affect how all looks like. I have manually increased sizes of fonts (much before pgmodeller installed) to make it smooth for my way of working. Here are my versions of QT:
![image](https://user-images.githubusercontent.com/553512/29938971-b22cf97a-8e8a-11e7-9122-ea4042be49bf.png)
As you see I have 2, but QT4 is only workaround for some older apps, QT5 is default.

**Comment by rkhaotix** [comment]
@archenroot  Great, thanks!

As I can see the font and window scaling are pretty good. The major issue is the icons. I've mentioned it in another issue or in twitter (don't remember) but the icons need to be redesigned in high resolution to fit 2K or 4K screens. That work will be done during pgModeler 1.0 development (I need to find a good designer to redraw every single icon :D ).

**Comment by truewar** [comment]
ArchLinux with cinnamon on Lenovo T440s

![2017-08-31-203148_1920x1080_scrot](https://user-images.githubusercontent.com/5078803/29939271-9d1e3372-8e8b-11e7-8b9a-b852d6ef71bd.png)

**Comment by rkhaotix** [comment]
@truewar Try to initialize pgModeler from console this way:

```$> QT_AUTO_SCREEN_SCALE_FACTOR=0  QT_SCALE_FACTOR=1 pgmodeler```

This will avoid the Qt built-in scale routines to be activated. This can work in some OSes and WM.

**Comment by truewar** [comment]
@rkhaotix I confirm it works :+1:

**Comment by archenroot** [comment]
@rkhaotix I think I remember already our discussion about 4K scale support maybe 1 year back +-. As you back in time mentioned regarding icons it requires complete creation of new set (in general it is not big issue for me when using it), again good stuff done here

**Comment by cloud-rocket** [comment]
@rkhaotix, disabling qt scaling works great! I think you should add this option in configuration.

Thanks

**Comment by brainwane** [comment]
I'm on Debian 9.2 (stretch) and prefixing my `pgmodeler` invocation with `QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=1` worked well to deal with this problem. Thanks @rkhaotix!

**Comment by juusechec** [comment]
I've make a bash script to execute pgmodeler from the compiled path. With this you can make execute script from anywhere (for example, to do a launcher without installing pgmodeler in system). Only create a text file with name `start_pgmodeler_launcher.sh` in root of pgmodeler repo.

```sh
#!/bin/bash
script="$(readlink -f $0)"
basename="$(dirname $script)"
echo "executing $script from $basename"
cd $basename
export LD_LIBRARY_PATH=/lib64:/usr/lib:$basename/libpgmodeler_ui:$basename/libpgmodeler:$basename/libpgconnector:$basename/libparsers:$basename/libutils:$basename/libobjrenderer
QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=1 $basename/main/pgmodeler
```

**Comment by fcolecumberri** [comment]
@rkhaotix I was also having a problem scaling problem, in my case with my gentoo/linux with mate environment, the text was fine, but the images were huge (so huge the window was bigger than the monitor) the strange part is that, same machine, same monitor ubuntu-mate worked fine, and that answer finally helped me, thanks

**Comment by Maxzor** [comment]
Is there a way to disable qt scaling in windows?
