### ISSUE TITLE
shadowbuild fails

### ISSUE THREAD

**Issue by ghost** [pgmodeler/pgmodeler#992]
With v0.9.0

No problem with a normal build,
shadowbuild fails on
     In file included from ../../../../git-pgmodeler/libpgmodeler_ui/src/modelwidget.h:31:0,
     from ../../../../git-pgmodeler/libpgmodeler_ui/src/pgmodelerplugin.h:28,
     from ../../../../git-pgmodeler/plugins/dummy/src/dummy.h:28,
     from ../../../../git-pgmodeler/plugins/dummy/src/dummy.cpp:19:
     ../../../../git-pgmodeler/libpgmodeler_ui/src/messagebox.h:28:10: fatal error: ui_messagebox.h: Bestand of map bestaat niet
 #include "ui_messagebox.h"

**Comment by rkhaotix** [comment]
Currently, shadow builds aren't supported.

Em 4 de set de 2017 4:11 AM, "kneeke" <notifications@github.com> escreveu:

With v0.9.0

No problem with a normal build,
shadowbuild fails on
In file included from ../../../../git-pgmodeler/libpgmodeler_ui/src/
modelwidget.h:31:0,
from ../../../../git-pgmodeler/libpgmodeler_ui/src/pgmodelerplugin.h:28,
from ../../../../git-pgmodeler/plugins/dummy/src/dummy.h:28,
from ../../../../git-pgmodeler/plugins/dummy/src/dummy.cpp:19:
../../../../git-pgmodeler/libpgmodeler_ui/src/messagebox.h:28:10: fatal
error: ui_messagebox.h: Bestand of map bestaat niet
#include "ui_messagebox.h"

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pgmodeler/pgmodeler/issues/992>, or mute the thread
